//
//  CategoryNormChinese.swift
//  Supermarket
//
//  Created by cheung gary on 5/5/2025.
//


import Foundation

/// “水果” 子分類下的 norm → 中文 映射
let subCategoryNormToChinese: [String: [String: String]] = [
  "水果": [
    "apple":        "蘋果",
    "avocado":      "牛油果",
    "banana":       "香蕉",
    "blackberry":   "黑莓",
    "blueberry":    "藍莓",
    "calamansi":    "金橘",
    "cherry tomato":"櫻桃小番茄",
    "coconut":      "椰子",
    "dragon fruit": "火龍果",
    "durian":       "榴槤",
    "grape":        "葡萄",
    "grapefruit":   "葡萄柚",
    "kiwi":         "奇異果",
    "lemon":        "檸檬",
    "longan":       "龍眼",
    "mandarin":     "橘子",
    "orange":       "橙",
    "pear":         "梨",
    "pineapple":    "菠蘿",
    "pomelo":       "柚子",
    "raspberry":    "樹莓",
    "strawberry":   "士多啤梨",
    "sun plum":     "太陽李",
    "tomato":       "番茄",
    "watermelon/hamimelon/papaya/melon":   "西瓜,木瓜,哈密瓜,香瓜",
    "others":       "其他",
    "mango":       "芒果"
  ],
  "蔬菜": [
    "mushroom":                      "蘑菇",//
    "sweet potato":                  "番薯",//
    "bell pepper":                   "甜椒",//
    "cherry tomatoes":               "車厘茄",//
    "potato":                        "薯仔",//
    "sweet bean":                    "四季豆",
    "tomatoes":                      "番茄",//
    "springonion/ginger/garlic":    "蔥薑蒜",//
    "herbs":                         "香草",//
    "choi sum":                      "菜心",//
    "cucumber":                      "黃瓜",//
    "lettuce":                       "生菜",
    "onion":                         "洋蔥",//
    "pumpkin":                       "南瓜",//
    "asparagus":                     "蘆筍",//
    "broccolini":                    "西蘭花",//
    "cabbage":                       "高麗菜",
    "others":                        "其他",
    "carrot":                         "紅蘿蔔/甘筍",//
    "corn":                           "栗米",//
    "pak choi":                       "小白菜",
    "pak choy":                       "小白菜",    
    "spinach":                        "菠菜",//
    "baby corn":                      "栗米筍",//
    "bean sprout":                    "豆芽",//
    "cauliflower":                    "椰菜花",
    "celery":                         "西芹",//
    "chinese lettuce":                "唐生菜",
    "eggplant":                       "茄子",//
    "green hydro":                    "水培蔬菜",
    "indian lettuce":                 "油麥菜",//
    "okra":                           "秋葵",//
    "radish":                         "白蘿蔔",
    "salad mix":                      "沙律菜",//
    "zucchini":                       "翠玉瓜",//
    "a vegetable sprout":             "菜苗",//
    "bamboo shoots":                  "竹筍",//
    "buddhism melon":                 "佛手瓜",//
    "celtuce":                        "萵筍",//
    "chinese kale":                   "芥蘭",//
    "round cabbage":                 "椰菜",
    "wong choi":                 "旺菜",//
    "kale":                 "羽衣甘藍",//
  ],
  
    "汽水": [
      "7 up free soft drink":                        "七喜輕怡汽水",
      "7 up soft drink":                             "七喜汽水",
      "barebells barebells rtd high protein milkshake 330ml - chocolate": "Barebells高蛋白奶昔",
      "BUNDABERG":                                   "賓得寶",
      "CALPIS Calpis Soda":                          "可爾必思",
      "casino delices traditional lemonade delices": "Casino Delices",
      "celsius celsius® fitness drink 325ml":        "Celsius® 健身飲料",
      "coca-cola bottle":                            "可口可樂（瓶裝）",
      "coca-cola can":                               "可口可樂（罐裝）",
      "coca-cola lemon":                             "可口可樂檸檬味",
      "coca-cola plus":                              "可口可樂 Plus",
      "coca-cola zero bottle":                       "可口可樂Zero（瓶裝）",
      "coca-cola zero can":                          "可口可樂Zero（罐裝）",
      "crystal spring":                              "碧泉",
      "dash sparkling mango 330 ml":                 "Dash 氣泡水",
      "efferve drink":                               "Efferve ",
      "ESSENTIAL WAITROSE":                          "Essential Waitrose ",
      "evian sparkling":                             "依雲氣泡水",
      "famous soda":                                 "Famous Soda",
      "fanta grape flavoured soda":                  "芬達葡萄味汽水",
      "fanta orange flavoured soda":                 "芬達橙味汽水",
      "monster energy drink":                        "魔爪能量飲料",
      "monster ultra energy drink":                  "魔爪 Ultra 能量飲料",
      "nocco nocco lemon":                           "NOCCO",
      "okf sparkling":                               "OKF 氣泡水",
      "on gold stand. protein shake chocolate":      "ON Gold Standard",
      "ooha sparkling":                              "OOHA 氣泡水",
      "pepsi cola":                                  "百事可樂",
      "pepsi cola No Sugar":                         "百事可樂無糖",
      "perrier magnetice":                           "法國巴黎果味礦泉水",
      "pocari ion supply drink":                     "寶礦力水特",
      "pokka sapporo drink":                         "Pokka Sapporo",
      "red bull energy drink":                       "紅牛能量飲料",
      "remedy kombucha":                             "Remedy 康普茶",
      "ribena lightly sparkling":                    "Ribena 淡味氣泡水",
      "ribena sparkling blackcurrant drink can case 24 x 320ml": "利賓納",
      "saitou drink":                        "Saitou 飲料",
      "san benedetto spark.mineral water 1.5l":      "聖碧濤 氣泡礦泉水",
      "Meadows Sparkling":                           "Meadows 氣泡水",
      "Meadows Soda Water":                          "Meadows 梳打水",
      "meadows cola":                                "Meadows 可樂",
      "SANGARIA":                                    "新加利亞汽水",
      "sarsae sparkling sarsa drink":                "沙示汽水",
      "schweppes ginger beer":                      "玉泉薑汁啤酒",
      "schweppes soda other flv":                    "玉泉其他口味汽水",
      "schweppes soda Lemonade":                     "玉泉檸檬口味梳打水",
      "schweppes soda":                              "玉泉蘇打水",
      "schweppes cream soda":                        "玉泉忌廉汽水",
      "Schweppes tonic water":                       "玉泉湯力水",
      "schweppes +c lemon flavoured soda":           "玉泉+C檸檬梳打",
      "Schweppes Dry Ginger":                        "玉泉乾薑啤",
      "CHI FOREST Sparkling Water":                  "元氣森林",
      "suntory c.c. lemon":                          "三得利 C.C",
      "sunkist sparkling lemonade":                  "新奇士 有氣檸檬汁",
      "vita Sparking":                               "維他™氣泡檸檬茶",
      "waitrose lemonade with juice":                "Waitrose",
      "Watson soda":                                 "屈臣氏梳打水",
      "Watson tonic water":                          "屈臣氏湯力水",
      "Woolworths Soda Wate":                        "Woolworths 梳打水",
      "Woolworths Tonic Water":                      "Woolworths 湯力水",
      "CHANG Soda":                                  "泰象啤",
      "EVERVESS Evervess Soda":                      "依維世梳打水",
      "fentimans rose lemonade":                     "Fentimans 玫瑰檸檬水",
      "Fever Tree tonic water":                      "熱樹湯力水",
      "SAN PELLEGRINO Sparkling":                    "聖培露有氣礦泉水",
      "Perrier Sparkling":                           "法國巴黎礦泉水",
      "known stranger sparkling":                    "益生元氣有氣果汁",
      "libogen drink":                               "力保健"
    
    ],
    
      "即飲茶類、咖啡、奶茶": [
        "authentic tea house taiwan jing-xuan oolongtea": "淳茶舍冷萃台灣金萱烏龍茶",
        "c'estbon black tea original tea": "怡寶佐味茶事紅茶原味茶飲料",
        "c'estbon chrysanthemum tea": "怡寶菊花茶原味茶飲料",
        "c'estbon lemon tea": "怡寶至本清潤檸檬茶",
        "c'estbon oolong tea original tea": "怡寶烏龍茶",
        "cha xiao kai tea drinks": "茶小開茶飲",
        "chai li won sugarfree tea": "茶裏王無糖日式綠茶",
        "crystal spring green tea drink": "晶泉綠茶飲料",
        "dai pai dong lemon tea": "大排檔港式檸檬茶",
        "dydo leaf green tea": "大島茶葉綠茶",
        "four seas lemon tea": "四洲檸檬茶",
        "haruna produce haruna the honey black tea": "Haruna Produce蜂蜜紅茶",
        "haruna produce lucafe houjicha": "Haruna Produce Lucafe焙茶",
        "healthworks drink": "健康工房飲品",
        "hi-c ceylon lemon tea": "陽光錫蘭檸檬茶",
        "hi-c chrysanthemum tea": "陽光菊花茶",
        "hi-c lychee honey tea": "陽光荔枝蜜茶",
        "hi-c mandarin tea": "陽光橘子茶",
        "hoi tin tong herbs tea": "海天堂草本茶",
        "hung fook tong drink": "鴻福堂鮮製飲品",
        "inabaen black oolong tea": "稻葉園黑烏龍茶",
        "itikoen tea": "伊藤園茶飲",
        "jia duo bao herbal tea": "加多寶涼茶",
        "kirin afternoon lemon tea": "麒麟午後紅茶檸檬紅茶",
        "kirin afternoon tea lemon": "麒麟午後紅茶檸檬紅茶",
        "kirin afternoon tea straight": "麒麟午後紅茶原味",
        "kirin rich green tea": "麒麟生茶",
        "kochakaden craftea lemon tea": "紅茶花伝CRAFTÉA檸檬紅茶",
        "kochakaden craftea orange black case": "紅茶花伝CRAFTÉA橙茶飲料",
        "kochakaden craftea peach tea": "紅茶花伝CRAFTÉA蜜桃茶",
        "lotte tea": "樂天初飲初樂",
        "meadows dahongpao oolong tea": "Meadows大紅袍烏龍茶",
        "meadows grosvenor momordica": "Meadows羅漢果茶",
        "meadows imperatae cane drink": "Meadows竹蔗茅根飲品",
        "meadows jasmine tea": "Meadows茉莉花茶",
        "meko passion fruit and orange fruit tea": "MEKO聯乘水果茶",
        "mr. kon ice tea": "康師傅冰紅茶",
        "mzk life honey sugar fig tea": "花研草說無花蜂糖潤咳茶",
        "mzk life osmanthus & snow pear tea": "花研草說桂花雪梨潤肺茶",
        "nongfu spring oriental leaf": "農夫山泉東方樹葉茶飲",
        "nongfu spring tea pi tea": "農夫山泉茶π茶飲",
        "original taste drink": "原味家作飲品",
        "original taste chrysanthemum w honey": "原味本舖蜂蜜菊花茶",
        "original taste fig apple & pear": "無花果蘋果雪梨茶",
        "original taste pear sichuan loquat": "鮮枇杷雪梨茶",
        "pura blended oolong tea": "PURA綜合烏龍茶",
        "pure life hk leys tea": "PURELIFEHKLeysTea",
        "rikyu chasaku honey green tea": "利休茶作蜂蜜綠茶",
        "rikyu chasaku japanese style sencha tea": "利休茶作日式煎茶",
        "robiff oolong tea": "津路烏龍茶",
        "robiff → oolong tea": "津路烏龍茶",
        "royal t garden premium oolong tea beverage": "御茶園冷山茶王烏龍茶飲品",
        "ruhn chan herbal tea": "清潤涼茶",
        "sensa cools herbal": "清熱酷飲品",
        "suntory iyemon green tea": "伊右衛門綠茶",
        "suntory jasmine oolong tea": "三得利茉莉烏龍茶",
        "suntory oolong tea": "三得利烏龍茶",
        "tao ti apple green tea": "道地蘋果綠茶",
        "tao ti green tea (honey)": "道地蜂蜜綠茶",
        "tao ti honey green tea": "道地蜂蜜綠茶",
        "tao ti kyoho grape black tea": "道地巨峰葡萄紅茶",
        "tao ti lemon black tea": "道地檸檬紅茶",
        "tao ti lemon with honey green tea": "道地檸檬(蜂蜜)綠茶",
        "tao ti lychee black tea": "道地荔枝紅茶",
        "tao ti mandarin green tea": "道地蜂蜜柑桔綠茶",
        "tao ti mandarin lemon": "道地百果園柑桔檸檬微碳酸",
        "tao ti orange flavour black tea": "道地橙紅茶",
        "tao ti pineapple green tea": "道地菠蘿綠茶",
        "tao ti sup oolong tea": "道地極品烏龍茶",
        "tao ti supreme chrysanthemum oolong tea": "道地極品菊花烏龍茶",
        "tao ti supreme genmaicha": "道地極品玄米茶",
        "tao ti supreme light barley tea": "道地極品清。麥茶",
        "vita cold brew no sugar puerh tea drink": "維他無糖冷泡茶高山普洱",
        "vita cold brew no sugar tie guan yin": "維他無糖冷泡茶鐵觀音",
        "vita gor yin hai icy pink grapefruit tea": "維他菓然系冰震紅西柚茶",
        "vita honey chrysanthemum tea": "維他蜜糖菊花茶",
        "vita honey lemon tea": "維他蜂蜜檸檬茶",
        "vita lemon tea": "維他檸檬茶",
        "vita lime lemon tea": "維他青檸檸檬茶",
        "vita low sugar tea": "維他低糖檸檬茶",
        "vita supericy lemon tea": "維他SUPERICY檸檬茶",
        "yushan double leaf lemon tea": "御山雙葉檸檬茶",
        "boss coffee": "BOSS黑咖啡",
        "dai pai dong hk style coffee": "大排檔港式咖啡",
        "escafe smoovlatte hazelnut flavour coffee": "雀巢咖啡Smoovlatte榛子味咖啡",
        "nescafe cafe latte aluminum": "雀巢拿鐵",
        "nescafe coffee": "NESCAFÉ咖啡",
        "nescafe nescafe coconut americano": "雀巢椰青美式咖啡",
        "nescafe nescafe coconut latte": "雀巢絲滑椰奶咖啡",
        "nescafe nescafe milk & sugar coffee": "雀巢香滑咖啡",
        "nescafe americano coffee": "雀巢美式咖啡",
        "nescafe nanyang white coffee": "雀巢南洋白咖啡",
        "nescafe smoovlatte mocha": "雀巢絲滑朱古力味咖啡",
        "suntory premium boss black coffee": "Suntory Boss高級無糖黑咖啡",
        "ucc coffee": "UCC咖啡",
        "asahi wonda coffee": "朝日Asahi Wonda咖啡",
        "boss coffee latte": "BOSS拿鐵",
        "dai pai dong coffee": "大排檔港式咖啡",
        "doutor hinokiwami black sugar free coffee": "Doutor黑咖啡",
        "dydo barista's choice low sugar coffee": "大德微糖世界咖啡",
        "four seas premium coffee": "四洲香濃咖啡",
        "georgia coffee": "喬治亞咖啡",
        "kirin fire one day coffee": "麒麟FireOneDay直火黑咖啡",
        "kirin fire one day unsweetened latte": "麒麟FireOneDay無糖拿鐵",
        "mr brown blue mountain coffee": "伯朗藍山風味咖啡",
        "mr. brown black coffee": "伯朗醇黑咖啡",
        "mr. brown deluxe coffee": "伯朗經典咖啡",
        "nescafe extra shot coffee": "NESCAFÉ特濃即飲咖啡",
        "nescafe full roast coffee": "NESCAFÉ醇釀烘焙咖啡",
        "nescafe instant coffee drink": "NESCAFÉ即溶咖啡飲品",
        "nescafe korean cafe collection cafe latte": "NESCAFÉ韓系拿鐵咖啡",
        "nescafe korean cafe collection cold brew black coffee": "NESCAFÉ韓系冷萃黑咖啡",
        "nescafe rich coffee": "NESCAFÉ香濃咖啡",
        "nescafe smoovlatte": "NESCAFÉ絲滑拿鐵",
        "nescafe smoovlatte hazelnut coffee": "NESCAFÉ絲滑榛子拿鐵",
        "okf coffee": "OKF咖啡",
        "pokka premium milk coffee": "PokkaPremium牛奶咖啡",
        "sangaria coffee": "新加利亞咖啡",
        "starbucks coffee": "Starbucks咖啡飲品",
        "suntory craft boss black coffee": "SUNTORYCraftBoss無糖黑咖啡",
        "suntory craft boss cafe mocha": "SUNTORYCraftBoss摩卡咖啡",
        "suntory double impact less sgr coffee": "SUNTORYDoubleImpact低糖咖啡",
        "itoen green tea": "伊藤園綠茶",
        "itoen green tea w/ roasted rice tea": "伊藤園玄米茶",
        "itoen jasmine tea": "伊藤園茉莉綠茶",
        "itoen oi ocha genmaicha": "伊藤園玄米茶",
        "kochakaden craftea orange black tea": "紅茶花伝CRAFTÉA橙味紅茶",
        "kochakaden craftea peach tea beverage": "紅茶花伝CRAFTÉA蜜桃茶飲",
        "nescafe cold brew black aluminum": "雀巢冷萃無糖黑咖啡",
        "ruhn chan chrysanthemum tea": "潤湛菊花茶",
        "ruhn chan red date tea": "潤湛紅棗茶",
        "ruhn chan water chestnut & sugar cane": "潤湛馬蹄蔗水",
        "sangaria anatano ocha": "新加利亞抹茶",
        "vita hk style milk tea": "維他港式奶茶",
        "black & white classic milk tea": "黑白經典奶茶",
        "if thai milk tea": "IF泰式奶茶",
        "kam cha hk style milk tea": "金茶王港式奶茶",
        "meadows milk tea": "Meadows原味奶茶",
        "tai hing hk style milk tea": "太興港式奶茶",
        "tao ti supreme oolong milk tea": "道地極品烏龍奶茶",
        "uni president milk tea": "統一奶茶",
        "tao ti supreme meta slim tea": "道地極品纖解茶",
        "tao ti supreme oolong": "道地極品烏龍茶",
        "vita cold brew no sugar jasmine tea": "維他冷泡無糖香片茶",
        "authentic tea house oolong tea": "淳茶舍大紅袍烏龍茶",
        "tao ti supreme meta green tea": "道地極品解綠茶",
        "tao ti supreme meta tea": "道地極品解茶",
        "vita chrysanthemum tea": "維他菊花茶",
        "itoen tea":"伊藤園茶飲",
        "vita ceylon lemon tea": "維他錫蘭檸檬茶",
        "vita ya shi xiang lemon tea": "維他鴨屎香檸檬茶",
        "vita zero sugar lemon tea": "維他零糖檸檬茶",
        "nestea ice rush lemon tea": "雀巢冰極檸檬茶",
        "nestea lemon tea": "雀巢檸檬茶",
        "vita cold brew no sugar pure tea": "維他冷泡無糖高山普洱茶",
        "authentic tea house cloudy green tea": "淳茶舍雲抹日式綠茶",
        "authentic tea house jasmine green tea": "淳茶舍茉莉綠茶",
        "authentic tea house yinhao jasmine green tea": "淳茶舍銀毫茉莉綠茶",
        "vita cold brew no sugar puer tea": "維他冷泡無糖高山普洱茶",
        "vita cold brew no sugar ceylon lemon tea": "維他冷泡無糖鍚蘭檸檬茶",
        "vita cold brew no sugar oolong tea": "維他冷泡無糖烏龍茶",
        "vita low sugar chrysanthemum": "維他低糖菊花茶",
        "authentic tea house gyokuro green tea": "淳茶舍無糖玉露綠茶",
        "authentic tea house puer tea": "淳茶舍消茶普洱茶",
        "nestea honey pear tea": "雀巢蜂蜜雪梨茶",
        "tao ti supreme meta oolong tea": "道地極品纖解烏龍茶",
        "tao ti supreme osmanthus green tea": "道地極品桂花綠茶",
        "tao ti supreme tangerine peel tea": "道地極品橘皮香茶",
        "vita apple green tea": "維他蘋果綠茶",
        "vita gor yin hai icy peach tea": "維他菓然系冰震蜜桃茶",
        "vita lemon tea low sugar": "維他低糖檸檬茶",
        "vita gor yin hai apple & mango tea": "維他菓然系蘋果芒果茶",
        "authentic tea house cold brew green tea": "淳茶舍冷萃日式深蒸綠茶",
        "dai pai dong hk style milk tea": "大排檔港式奶茶",
        "kirin afternoon milk tea": "麒麟午後奶茶",
        "rikyu chasaku tea": "利休茶作茶飲",
        "vita apple jasmine": "維他清心棧飲品",
        "tao ti supreme light oolong tea": "道地極品清烏龍茶",
        "vita fresh lemon tea": "維他新鮮茶飲",
        "vita lemon tea sparkling zero sugar": "維他零糖氣泡檸檬茶",
        "vita lemon tea zero sugar": "維他零糖檸檬茶",
        "tao ti yashi xiang lemon tea": "道地鴨屎香茶飲",
        "vita cold brew no sugar dong ding ooling": "維他冷泡無糖凍頂烏龍茶",
        "vita gor yin hai icy lemon tea": "維他菓然系冰震檸檬茶",
        "vita japanese style peach tea": "維他日式蜜桃茶",
        "itamachi barley tea": "板町麥茶",
        
    
      ],
  
  "奶類、乳酪飲品": [
    "aboutea gold oolong milk tea": "盛致黃金烏龍奶茶",
    "anchor full cream uht milk": "安佳全脂牛奶",
    "anlene hi-cal low fat milk": "安怡高鈣低脂奶",
    "aus'mania milk": "Aus'Mania牛奶系列",
    "benecol original yogurt drink": "倍樂醇原味乳酪飲品",
    "binggrae flavoured milk": "Binggrae牛奶飲品系列",
    "black & gold full cream uht milk": "Black & Gold 全脂牛奶",
    "casino organic plain rice drink": "Casino有機米類飲品",
    "cheer organic fresh milk": "滋味有機鮮奶",
    "cow & gate milk": "牛欄 Milk Plus 兒童奶",
    "daioni organic milk": "Daioni 有機牛奶系列",
    "dairy kirishima milk": "霧島山麓全脂牛奶",
    "devondale milk": "澳洲德運牛奶系列",
    "dutch lady chocolate milk": "子母牌巧克力牛奶",
    "dutch lady milk": "子母牌牛奶系列",
    "dutch lday yogurt": "子母牌優格飲飲品",
    "emmi semi skimmed milk": "Emmi 半脫脂牛奶",
    "fred & chloe milk": "Fred & Chloe牛奶系列",
    "freshjoy fresh milk": "悅鮮活鮮牛奶",
    "harvey fresh milk": "澳洲哈維牛奶系列",
    "just pure drinking yoghurt": "純甄優格飲品系列",
    "kokuaji 3.6 fresh milk": "北海道特選3.6牛乳",
    "kowloon dairy soya milk drink": "維記豆奶系列",
    "kowloon dairy milk": "維記牛奶系列",
    "kowloon dairy yogurt": "維記乳酪飲品系列",
    "lactel uht semi skimmed milk": "Lactel UHT 半脫脂牛奶?",
    "macro organic milk": "Macro 有機奶系列",
    "meadow milk": "Meadow牛奶系列",
    "meiji milk": "明治牛奶系列",
    "mengniu low fat high calcium milk": "蒙牛低脂高鈣牛奶",
    "monmilk chewy milk beverage": "蒙牛真果粒",
    "nestle milk": "雀巢牛奶系列",
    "ovaltine rich chocolate malted milk": "阿華田濃滑朱古力麥芽奶",
    "pauls milk": "Pauls牛奶系列",
    "daioni organic semi skimmed milk": "Daioni 有機半脫脂牛奶",
    "pure organic rice milk": "Pure Harvest 有機米奶",
    "shiny milk": "每日鮮語牛奶系列",
    "soymilk": "豆漿",
    "the bridge bio rice drink": "The Bridge 有機米飲",
    "trappist dairy milk": "十字牌牛奶系列",
    "vita milk": "維他牛奶系列",
    "vitasoy australia soy milk": "維他奶 Australia 原味豆奶",
    "vitasoy calci plus drink": "維他鈣思寶豆奶系列",
    "vitasoy australia milk": "維他澳洲奶制品系列",
    "vitasoy bean milk": "維他奶豆奶系列",
    "vitasoy vita yoghurt flavor drink": "維他奶乳酪飲",
    "want want lactic acid drink": "旺仔乳酸飲品",
    "emmi premium milk": "伊美瑞士特級牛奶"
  ],
  "沖調飲品": [
    "ace sencha tea bag": "Ace 煎茶茶包",
    "ah huat extra rich": "亞發特濃白咖啡",
    "ah huat roast coffee": "亞發炭燒白咖啡",
    "ah huat white coffee": "亞發白咖啡",
    "ahmad fruit tea": "Ahmad Tea 水果茶",
    "authentic king chrysanthemum": "Authentic King 皇菊花茶",
    "authentic king imperate cane": "Authentic King 茅根茶",
    "belmio coffee cap": "Belmio膠囊咖啡系列",
    "blackgold legacy ginger tea": "Blackgold 黑金傳奇黑糖薑茶",
    "bob's red mill flaxseed meal": "Bob’s Red Mill 亞麻籽粉",
    "borbone nespresso coffee capsule": "Borbone 膠囊咖啡",
    "brooke bond pg tips tea": "PG Tips 茶包",
    "cafedirect roast coffee": "Café Direct 烘焙咖啡",
    "camellia treasure tea": "Camellia Treasure茶包系列",
    "casino coffee": "Casino咖啡粉/朱古力粉系列",
    "catalo drink": "Catalo飲品系列",
    "catalo oat milk": "Catalo燕麥奶系列",
    "celestial tea": "Celestial茶包系列",
    "chef kim honey citron tea": "金師傅蘆薈柚子茶",
    "chek hup coffee": "澤合咖啡系列",
    "clipper tea": "金舶英茶(英國)茶包系列",
    "costa coffee signature": "Costa Coffee 招牌咖啡",
    "coudo ginger tea": "Coudo 薑茶",
    "coudo honey citron tea": "高島蜂蜜柚子茶",
    "dai pai dong yuan yang": "大排檔鴛鴦系列",
    "dai pai dong milk tea powder": "大排檔奶茶系列",
    "dai pai dong coffee": "大排檔咖啡系列",
    "dai pai dong tea": "大排檔茶包系列",
    "dai pai dong drink": "大排檔即溶飲品系列",
    "daisho green veg drink": "Daisho 綠色蔬菜飲品",
    "damtuh ginger tea": "丹特薑茶",
    "dextro detrox d.glucose powder": "得力素能量葡萄糖粉",
    "dilmah earl grey tea": "迪爾瑪伯爵茶",
    "ediya coffee": "Ediya咖啡系列",
    "emerail tea": "貴茶茶包系列",
    "essential waitrose coffee": "Essential Waitrose咖啡系列",
    "food nation ginger tea": "Food Nation 薑茶",
    "g7 coffee": "G7咖啡系列",
    "gingen ginger tea": "真精薑茶系列",
    "golden swallow drink": "金燕子即沖飲品系列",
    "good day mocacinno 3in1": "Good Day 摩卡三合一咖啡",
    "green dot dot 100%": "綠點點即沖系列",
    "green dot dot soya milk": "綠點點豆奶系列",
    "greenmax black sesame meal": "綠源黑芝麻糊",
    "healthy green corn mustard": "健康綠玉米芥末粉",
    "healthy green sugar cane": "健康綠甘蔗粉",
    "ho cha tea box set": "好茶養生 盒裝系列",
    "ho cha tea pack set": "好茶養生 單包裝系列",
    "horlicks drink": "好立克飲品系列",
    "illy coffee": "意利咖啡系列",
    "indocafe coffee": "迎樂咖啡系列",
    "jaf tea": "佳福茶茶包系列",
    "jomeis fine foods cacao": "Jomeis Fine Foods飲品系列",
    "kai tsun tea": "啟贊茶飲系列",
    "kam cha drink": "Kam Cha飲品系列",
    "kapal api coffee": "火船牌咖啡",
    "key coffee drip on": "Key Coffee 滴漏咖啡",
    "kim guan guan kopi-coffee": "金冠冠馬來西亞咖啡",
    "kimbo coffee": "Kimbo咖啡系列",
    "kobe haikara coffee": "神戸齋藤珈琲店咖啡",
    "lavazza coffee": "Lavazza咖啡系列",
    "lipton tea bag": "立頓茶包系列",
    "lipton milk tea": "立頓奶茶系列",
    "luk yu tea bag": "陸羽茶包系列",
    "maxwell coffee": "麥斯威爾咖啡系列",
    "meadows original coffee 3in1": "Meadows 原味三合一咖啡",
    "melitta coffee": "美樂家咖啡系列",
    "milo": "美祿飲品系列",
    "mingcha tea": "明茶房茶包系列",
    "moccona coffee": "名仕咖啡系列",
    "movenpick capsules": "Mövenpick咖啡膠囊",
    "movevnpick gold original coffee": "Mövenpick咖啡",
    "mr & mrs bean": "Mr & Mrs Bean",
    "mr brown milk tea/coffee": "伯朗奶茶/咖啡",
    "mzk life tea": "花研草說茶飲系系列",
    "nanguo coconut lattle 330gm": "南國椰奶拿鐵 330克",
    "natural garden tea": "田園茶飲系列",
    "nescafe 1+1 unsweet coffe": "雀巢1+1無糖咖啡",
    "nescafe 1+2 coffee": "雀巢1+2原味咖啡",
    "nescafe 1+2 rich coffee": "雀巢1+2特濃咖啡",
    "nescafe 1+2 smooth&milk coffee": "雀巢咖啡1+2奶滑咖啡",
    "nescafe 3 in 1": "雀巢拉咖啡",
    "nescafe cafe viet": "雀巢越南咖啡",
    "nescafe classic coffee": "雀巢經典咖啡",
    "nescafe coconut latte": "雀巢椰奶咖啡",
    "nescafe dolce gusto coffee": "雀巢Dolce Gusto咖啡膠囊",
    "nescafe gold coffee": "雀巢金牌咖啡系列",
    "nescafe instant coffee": "雀巢即溶咖啡",
    "nescafe nc foldable umbrella": "雀巢折疊傘 (促銷贈品)",
    "nescafe white coffee": "雀巢白咖啡",
    "nescafe nescafe x sho-chan": "雀巢X Sho-Chan聯名咖啡",
    "nescafe premium cappuccino": "雀巢極品泡沫咖啡",
    "nescafe premium smoovlatte": "雀巢極品絲滑牛奶咖啡",
    "nescafe rich blend coffee": "雀巢醇品咖啡",
    "nestle coffee mate": "雀巢咖啡伴侶",
    "nestle nescafe gold blend": "雀巢金牌咖啡",
    "nestle choc drink": "雀巢巧克力飲品系列",
    "nitto black tea white": "Nitto 白毫烏龍茶",
    "oatbedient oat milk drink": "Oatbedient燕麥奶粉系列",
    "oh!fresh orange black coffee": "Oh!Fresh 橙味黑咖啡",
    "old town 2in1": "舊街場2合1咖啡",
    "old town 3in1 white coffee": "舊街場3合1白咖啡",
    "old town 3in1 hazelnut coffee": "舊街場3合1白咖啡(榛果味)",
    "on kee tea": "安記茶飲系列",
    "organic garden drink": "慈康農圃飲品系列",
    "osk 3 in 1": "OSK 三合一咖啡",
    "osk tea": "OSK茶包系列",
    "ovaltine": "阿華田飲品系列",
    "po ma almond powder": "寶馬杏仁粉",
    "pumuen org roast coffee": "珈琲人掛耳咖啡",
    "resiprocate org sumatra whole": "Resiprocate有機蘇門答臘咖啡豆",
    "rickshaw chinese teabags": "車仔茶包系列",
    "robert timms coffee": "羅伯特替姆斯咖啡系列",
     "select instant coffee": "佳之選 即溶咖啡",
    "select honey tea": "佳之選蜂蜜茶飲系列",
    "select tea bag": "佳之選茶包系列",
    "select drink": "佳之選即沖飲品系列",
     "sensory zero sensory zero": "Sensory Zero德用咖啡掛耳包盒裝",
     "starbucks latte": "星巴克奶泡即溶咖啡系列",
     "starbucks cappuccino": "星巴克意大利泡沬即溶咖啡系列",
     "starbucks caramel coffee": "星巴克焦糖即溶咖啡系列",
     "starbucks by roast coffee": "星巴克 烘焙咖啡",
     "starbucks house blend": "星巴克研磨咖啡粉系列",
     "starbucks coffee caps": "星巴克咖啡粉膠囊",
     "starbucks origami caffe verona": "星巴克caffè verona掛耳式滴漏咖啡",
     "starbucks caffe mocha": "星巴克朱古力即溶咖啡",
     "starbucks cappucino 4 x": "星巴克 卡布奇諾4入裝",
     "starbucks caramel coffee by": "星巴克 焦糖咖啡",
     "starbucks caramel latte premium": "星巴克 焦糖拿鐵高級混合",
     "starbucks colombia by nespresso": "星巴克 哥倫比亞咖啡膠囊",
     "starbucks colombia by starbucks": "星巴克 哥倫比亞咖啡",
     "starbucks decaf roast coffee": "星巴克 無咖啡因烘焙咖啡",
     "starbucks espresso nespresso coffee capsule": "星巴克 濃縮咖啡膠囊",
     "starbucks espresso roast coffee": "星巴克濃縮咖啡",
     "starbucks house blend by": "星巴克 經典混合咖啡",
     "starbucks house blend ground": "星巴克 經典混合研磨咖啡",
     "starbucks house blend lungo": "星巴克 經典混合長咖啡",
     "starbucks italian roast coffee": "星巴克 意大利烘焙咖啡",
     "starbucks latte 4 x": "星巴克 拿鐵4入裝",
     "starbucks latte macchiatto by": "星巴克 拿鐵瑪奇朵",
     "starbucks matcha latte premium": "星巴克 抹茶拿鐵高級混合",
     "starbucks pike place by": "星巴克 派克市場咖啡",
     "starbucks single origin guatemala": "星巴克 瓜地馬拉單品咖啡",
     "starbucks single origin sumatra": "星巴克 蘇門答臘單品咖啡",
    "starbucks single-origin guatemala by": "星巴克瓜地馬拉單品咖啡",
    "starbucks spring roast coffee": "星巴克春季烘焙咖啡",
    "starbucks starbucks® caffè verona™": "星巴克 維羅納咖啡",
    "starbucks starbucks® caramel flavoured": "星巴克 焦糖風味咖啡",
    "starbucks starbucks® house blend": "星巴克 經典混合咖啡",
    "starbucks starbucks® matcha latte": "星巴克 抹茶拿鐵",
    "starbucks starbucks® nespresso coffee capsule": "星巴克 Nespresso 咖啡膠囊",
    "starbucks starbucks® roast coffee": "星巴克 烘焙咖啡",
    "starbucks starbucks® single origin": "星巴克 單品咖啡",
    "starbucks starbucks® sunny day": "星巴克 晴天咖啡混合",
    "starbucks starbucks® toffee nut": "星巴克 太妃堅果風味咖啡",
    "starbucks starbucks® vanilla flavoured": "星巴克 香草風味咖啡",
    "starbucks sunny day blend": "星巴克 晴天混合咖啡",
    "starbucks vanilla coffee by": "星巴克 香草咖啡",
    "starbucks® ristretto shot by": "星巴克 濃縮咖啡萃取",
    "sticksology tea": "Sticksology茶包系列",
    "sweet garden drink": "薌園飲品系列",
    "swiss miss chocolate drink": "瑞士小姐朱古力飲品系列",
    "tai luen hong kong": "大聯港式紅茶茶膽",
    "tao ti lychee black": "桃子荔枝紅茶",
    "tao ti supreme jasmine": "桃子極品茉莉花茶",
    "tarza caffe coffee": "Tarza咖啡系列",
    "taster choice coffee": "Taster's Choice咖啡系列",
    "taster choice freeze dried": "Taster's Choice 冷凍乾燥咖啡",
    "taylors tea bag": "泰勒茶包系列",
    "te@espresso tea caps": "Te@Espresso茶膠囊系列",
    "teapigs tea bag": "Teapigs茶包系列",
    "ten ren tea": "天仁茗茶茶飲系列",
    "ten ren pu-er tea": "天仁茗茶 普洱茶",
    "ten ren ti koong": "天仁茗茶 天宮茶",
    "ten ren ti kuan": "天仁茗茶 天寬茶",
    "ten ren tung ting": "天仁茗茶 凍頂烏龍茶",
    "ten ren whole leaves": "天仁茗茶 散葉茶",
    "tsit wing coffe": "捷榮咖啡",
    "tsit wing tea bag": "捷榮茶包系列",
    "tsit wing milk tea":"捷榮奶茶系列",
    "tsit wing yuan yang": "捷榮鴛鴦",
    "twinings tea bag": "川寧茶包系列",
    "ucc coffee": "Ucc咖啡系列",
    "ueshima coffee": "上島咖啡咖啡系列",
    "ujinotsuyu jpn tea t-bag": "宇治之茶包",
    "van houten cocoa powder": "金鷹可可粉",
    "viaggio caps": "Viaggio咖啡膠囊",
    "waitrose tea bag": "Waitrose茶包系列",
    "waitrose coffee": "Waitrose咖啡系列",
    "way choy tea": "日月牌茶飲系列",
    "yu pin king tea": "御品皇茶包系列",
    "imperial choic tea": "御茗茶飲系列",
    "bovril yeast extract": "保衛爾酵母素"

   
],
  "果汁": [
      "beckers bester cloudy apple juice": "Beckers Bester德國雲蘋果汁",
      "bickford's natural lime juice cordial": "Bickford's天然青檸濃縮飲品",
      "black & gold drink": "Black & Gold果汁飲品系列",
      "casino bio organic multifruits pure juice": "Casino Bio有機雜果純果汁",
      "casino juice": "Casino果汁系列",
      "cawston apple rhubarb juice drink": "Cawston蘋果大黃汁飲品",
      "ceres juice": "Ceres 100果汁系列",
      "chung jung one red vinegar": "清淨園紅醋飲品系列",
      "cocomax coconut water": "Cocomax椰子水",
      "cocoway coconut water": "Cocoway椰子水",
      "community co. coconut water": "Community Co.椰子水",
      "cou-su vinegar": "一斤果醋系列",
      "coudo concentrated mango juice": "Coudo濃縮芒果汁",
      "del monte juice": "地捫果汁系列",
      "dole water jelly mango": "Dole芒果啫喱水飲品",
      "don simon apple juice": "Don Simon蘋果汁",
      "don simon orange juice with pulp": "Don Simon有果肉橙汁",
      "don simon peach & grape juice": "Don Simon桃子提子混合汁",
      "don simon red grape juice": "Don Simon紅提子汁",
      "essential waitrose pure apple juice": "Essential Waitrose純蘋果汁",
      "food nation natural coconut water": "Food Nation天然椰子水",
      "four seas tsubu tsubu orange drink": "四洲粒粒橙味飲品",
      "fresh berries juice": "鮮莓果汁",
      "golden circle apple juice": "Golden Circle蘋果汁",
      "golden circle orange juice": "Golden Circle橙汁",
      "gua juice": "GUA果汁飲品系列",
      "hi-c apple juice": "陽光蘋果飲品汁",
      "hi-c lemon blackcurrant": "陽光檸檬黑加侖子飲品",
      "hi-c orange juice": "陽光橙汁飲品",
      "hi-c pineapple": "陽光菠蘿汁飲品",
      "homegrown cold pressed juice": "Homegrown冷壓果汁系列",
      "homegrown probio kiwi juice": "Homegrown益生菌奇異果汁",
      "homegrown raw energy cold pressed juice": "Homegrown活力冷壓果汁",
      "if 100% coconut water": "iF 100%椰子水",
      "if 100% coconut water with coconut pulp": "iF 100%椰子水（椰果肉）",
      "if 100% natural coconut water": "iF 100%天然椰子水",
      "if peach juice drink": "iF桃味果汁飲品",
      "itamachi coconut milk drink": "Itamachi椰奶飲品",
      "ja aoren premium apple juice": "JA Aoren優質蘋果汁",
      "james white organic carrot & apple juice": "James White有機紅蘿蔔蘋果汁",
      "jax coco coconut water": "Jax Coco椰子水",
      "kagome apple mixed juice": "Kagome蘋果混合果汁",
      "kagome carrot mixed juice": "Kagome紅蘿蔔混合果汁",
      "kagome grape mixed juice": "Kagome提子混合果汁",
      "kagome mango mixed juice": "Kagome芒果混合果汁",
      "kagome mixed carrot juice": "Kagome混合紅蘿蔔果汁",
      "kagome mixed mango juice": "Kagome混合芒果果汁",
      "kagome tomato juice": "Kagome蕃茄汁",
      "kagome vegetable juice": "Kagome蔬菜汁",
      "koh coconut water": "KOH椰子水",
      "malee coconut water": "Malee椰子水",
      "meadows coconut water": "Meadows椰子水",
      "meko coconut water": "Meko椰子水",
      "meko coconut water case": "Meko椰子水箱裝",
      "meko pure coconut water": "Meko純椰子水",
      "meysu juice": "Meysu果汁系列",
      "minute maid orange juice drink": "Minute Maid橙味果汁飲品",
      "minute maid qoo apple juice drink": "Qoo蘋果汁飲品",
      "minute maid qoo blackcurrant juice drink": "Qoo黑加侖子汁飲品",
      "minute maid qoo peach juice drink": "Qoo桃汁飲品",
      "minute maid qoo white grape juice drink": "Qoo白提子汁飲品",
      "minute maid white grape juice drink": "美粒果白提子汁飲品",
      "mr. juicy apple juice": "維他果汁先生蘋果汁",
      "mr. juicy coconut water": "維他果汁先生椰子水",
      "mr. juicy orange juice": "維他果汁先生橙汁",
      "mysmoothie smoothie": "Mysmoothie果昔系列",
      "nature's sen organic pomegranate juice": "Nature's Sen有機果汁系列",
      "nissin green juice": "日清青汁系列",
      "ocean spray cranberry juice": "Ocean Spray果汁飲品系列",
      "okf farms yogurt": "OKF乳酪飲品系列",
      "paldo pororo drink": "Pororo飲品系列",
      "popper juice apple juice": "Popper蘋果汁",
      "rabenhorst juice": "Rabenhorst果汁系列",
      "ready orange juice with pulp": "Ready有果肉橙汁",
      "ready pineapple juice": "Ready菠蘿汁",
      "ribena blackcurrant drink": "Ribena黑加侖子飲品",
      "ribena concentrate": "Ribena濃縮黑加侖子",
      "simply kids juice": "Simply Kids果汁系列",
      "sunkist sparkling grapefruit juice drink": "Sunkist有氣西柚汁飲品",
      "sunquick orange cordial": "Sunquick橙味濃縮果汁",
      "sunraysia cranberry juice": "Sunraysia蔓越莓汁",
      "sunraysia prune juice": "Sunraysia西梅汁",
      "sunsweet prune juice": "Sunsweet西梅汁",
      "tao ti grape kyoho juice": "道地巨峰提子汁",
      "tao ti lychee juice drink": "道地荔枝果汁飲品",
      "tao ti mandarin lemon juice drink": "道地柑橘檸檬果汁飲品",
      "tao ti pak gor yuen mandarin lemon juice drink": "道地白果園柑檸果汁飲品",
      "the berry company juice": "The Berry Company果汁系列",
      "tian di no 1 apple vinegar drink": "天地一號蘋果醋飲品",
      "tree top apple juice": "Tree Top蘋果汁",
      "tree top orange juice": "Tree Top橙汁",
      "ufc coconut water": "UFC椰子水",
      "v8 vegetable juice": "V8蔬菜汁",
      "van nahmen apricot nectar": "Van Nahmen杏桃果汁",
      "vita apple juice": "維他蘋果汁",
      "vita blackcurrant juice": "維他黑加侖汁",
      "vita coco coconut water": "Vita Coco椰子水",
      "vita guava juice": "維他番石榴汁",
      "vita guava juice drink": "維他番石榴汁",
      "vita juice guava drink": "維他果汁番石榴飲品",
      "vita mango juice drink": "維他芒果果汁",
      "welch's grape juice": "Welch's提子汁",
      "welch's pure grape juice": "Welch's純提子汁",
      "welch's zero sugar grape juice": "Welch's零糖提子汁",
      "yeshu coconut juice beverage": "椰樹椰汁飲品",
      "it's manuka drink":"天然麥盧卡蜜糖飲品系列"
      ],
  "運動及能量飲品": [

    "100plus active electro drink": "100PLUS 電解質運動飲品",
     "alienergy electrolyte drink": "外星人電解質飲品",
     "aquarius electrolyte replenishment drink": "水動樂電解質補充飲品",
     "aquarius electrolyte replenishment drink case": "水動樂電解質補充飲品(箱裝）",
     "aquarius electrolytes replenish drink zero": "水動樂無糖電解質補充飲品",
     "aquarius electrolytes replenishment drink powder": "水動樂電解質補充飲品粉裝",
     "barebells milk shake": "Barebells乳清蛋白奶昔",
     "celsius fitness drink sparkling white peach": "Celsius健身氣泡飲白桃味",
     "drinkazine energy drink case 20 x 800 ml": "解渴誌沛力特箱裝）",
     "eastroc vitamin energy drink": "東鵬維生素特飲",
     "gatorade drinks": "Gatorade佳得樂運動飲品",
     "gnc protein drinks": "GNC蛋白質飲品",
     "labrada protein drinks": "Labrada蛋白質飲品",
     "lean body protein shake": "Lean Body高蛋白奶昔",
     "libogen tonic drink": "Libogen精力補身飲品",
     "lucozade energy drink low sugar orange": "葡萄適低糖橙味能量飲品",
     "lucozade energy drink orange flavour": "葡萄適橙味能量飲品",
     "lucozade energy drink original": "葡萄適原味能量飲品",
  "lucozade sport orange": "葡萄適Sport橙味運動飲品",
  "monster energy drink": "Monster能量飲品",
  "monster energy drink ultra": "Monster Ultra系列能量飲品",
  "monster mango loco": "Monster 芒果能量飲品",
  "monster peachy keen": "Monster 蜜桃能量飲品",
  "oronamin c oronamin c": "Oronamin C維他命飲品",
  "pocari ion supply drink": "寶礦力水特電解質飲品",
  "pocari sweat ion supply drink case": "寶礦力水特電解質飲品（箱裝）",
  "pocari ion water low kcal": "寶礦力水特低卡電解質水",
  "prime drinks": "Prime電解質飲品",
    "red bull apple muscat sparkling energy drink": "Red Bull青蘋果麝香葡萄味能量飲品",
    "red bull energy drink": "Red Bull能量飲品",
    "red bull kyoho grape": "Red Bull巨峰提子味能量飲品",
    "red bull pomelo sparkling energy drink": "Red Bull柚子味氣泡能量飲品",
    "red bull drink": "Red Bull能量飲品系列",
    "sis hydro": "SIS電解補水水溶片系列",
    "sis hydro tablet lemon": "SIS 水解檸檬味片",
    "v energy original": "V能量飲品",
    "weider in jelly energy in": "WEIDER IN JELLY能量果凍",
    "you c1000 vitamin": "You-C1000維他命飲品系列",
  ],
  "涼茶": [
    "healthworks hawthorn apple":"健康工房山楂蘋果飲品",
    "healthworks lemon yiyiren":"健康工房檸檬薏米飲品",
    "healthworks rock sugar with pear":"健康工房冰糖雪梨飲品",
    "healthworks self heal spike":"健康工房夏枯草飲品",
    "healthworks sugarcane rhizoma imperatae and sea coconut":"健康工房竹蔗茅根海底椰飲品",
    "healthworks sugarcane sea coconut":"健康工房竹蔗海底椰飲品",
    "healthworks sugarcane seacoconut":"健康工房竹蔗茅根海底椰飲品",
    "hoi tin tong drinks":"海天堂涼茶系列",
    "hung fook tong american ginsing with honey":"鴻福堂花旗參蜜飲品",
    "hung fook tong brewing american ginseng":"鴻福堂花旗參系列飲品",
    "hung fook tong chrysanthemum with honey":"鴻褔堂銀菊露飲品",
    "hung fook tong fig w apple water chestnut":"鴻福堂馬蹄無花果茶",
    "hung fook tong floral herbal":"鴻福堂五花茶飲品",
    "hung fook tong ginseng with honey":"鴻福堂人參蜜飲",
    "hung fook tong honey drk w fritillary loquat leaves":"鴻福堂川貝枇杷潤肺茶",
    "hung fook tong honey drk w mulberry mulberry leaf":"鴻福堂桑椹桑葉茶",
    "hung fook tong honey w chuan bei loquat leave":"鴻福堂川貝枇杷蜜飲品",
    "hung fook tong hung fook tong pear and chrysanthemum":"鴻福堂雪梨菊花茶飲品",
    "hung fook tong imperatae cane":"鴻福堂竹蔗茅根飲品",
    "hung fook tong pear":"鴻福堂雪梨茶",
    "hung fook tong salted lime":"鴻福堂咸青檸飲品",
    "hung fook tong salted mandarin":"鴻福堂咸柑桔飲品",
    "hung fook tong sour plum":"鴻福堂酸梅湯飲品",
    "hung fook tong sugarcane juice":"鴻福堂竹蔗汁",
    "hung fook tong tangerine peel mandarin":"鴻福堂陳皮柑桔飲品",
    "jia duo bao herbal":"加多寶涼茶系列",
    "kirin rich green series origin flavor":"nonshow",
    "tao ti supreme meta":"nonshow",
    "tao ti supreme meta slim":"nonshow",
    "vedan winter melon":"味丹心茶道冬瓜茶",
    "vita apple jasmine juice":"維他清心棧冬蘋果茉莉飲品",
    "vita sugar cane imperatae":"維他清心棧冬竹蔗茅根飲品",
    "vita tsing sum zhan honey lime healthy":"維他清心棧冬蜜青檸飲品",
    "vita tsz apple and jasmine":"維他蘋果茉莉飲品",
    "vita tsz sugar cane and imperatae":"維他竹蔗茅根飲品",
    "yeo s grass jelly":"楊協成清涼爽",
    "yeo s yeo s herb set":"楊協成涼茶套裝",
    "yeo s yeo s white gourd":"楊協成冬瓜茶",

    "hung fook tong canton love pea vine":"鴻褔堂雞骨草",
    "hung fook tong common selfheal fruit spike":"鴻褔堂夏枯草",
    "hung fook tong grosvenor momordica fruit":"鴻褔堂無糖羅漢果",
    "hung fook tong sugarcane and sea coconut with carrot":"鴻褔堂竹蔗甘筍海底椰飲品",
    "meadows grosvenor momordica":"Meadows羅漢果飲品",
    "meadows imperatae cane":"Meadows竹蔗茅根飲品",
    "mj x hft lemon coix seeds":"菓汁先生X鴻福堂檸檬薏米飲品",
    "mj x hft mj x hft red bean coix seeds":"菓汁先生X鴻福堂紅豆薏米飲品",
    "mr juicy honey pear juice":"菓汁先生蜂蜜雪梨果汁飲品",
    "mr juicy sugarcane water chestnut juice":"菓汁先生竹蔗馬蹄果汁飲品",
    "mzk life honey sugar fig":"花研草說冰糖蜂蜜皇菊茶",
    "mzk life osmanthus snow pear":"花研草說桂花雪梨潤肺茶",
    "original taste carrot pear":"原味家作甘筍雪梨茶",
    "original taste chrysanthemum w honey":"原味家作原味家作菊花蜜露",
    "original taste fig apple pear":"原味家作無花果蘋果雪梨茶",
    "original taste fresh citrus with coix seed":"原味家作鮮柑桔薏米露",
    "original taste fresh lemon with coix seed":"原味家作鮮檸檬薏米露",
    "original taste fresh peach with coix seed":"原味家作鮮蜜桃薏米露",
    "original taste pear sichuan loquat":"原味家作雪梨川貝枇杷蜜",
    "sensa cools herbal chrysanthemum": "清熱酷百花菊茶",
    "sensa cools herbal green": "清熱酷草本綠茶",
    "sensa cools herbal lemon": "清熱酷草本檸檬茶"
    
  ],
  "啤酒": [
    "asahi": "朝日啤酒啤酒系列",
    "blue girl": "藍妹啤酒",
    "blue girl light": "藍妹清啤",
    "blue ice": "藍冰啤酒",
    "blue ice filtered": "藍冰啤酒",
    "boddingtons pub ale": "Boddingtons啤酒",
    "brewdog": "Brewdog啤酒系列",
    "bruck lager": "布萊特啤酒",
    "budweiser": "百威啤酒",
    "carbon brews feels good man wheat": "Carbon Brews Feels Good Man啤酒",
    "carlsberg": "嘉士伯啤酒",
    "carlsberg danish brew":"嘉士伯巨罐金牌啤酒",
    "chang": "泰象啤酒",
    "corona extra": "Corona啤酒",
    "erdinger": "艾丁格啤酒系列",
    "gs retail youus": "Gs Retail Youus手工啤酒系列",
    "guinness": "健力士黑啤酒",
    "gweilo beer pale ale": "鬼佬啤酒",
    "harbin": "哈爾濱啤酒",
    "heineken": "喜力啤酒",
    "heineken silver": "喜力星銀啤酒",
    "hite 1933": "海特啤酒系列",
    "hoegaarden": "好卡頓啤酒系列",
    "jolly shandy lemon": "樂怡仙地",
    "kingway": "金威啤酒",
    "kirin ichiban": "麒麟一番搾啤酒",
    "kirin ichiban japan prime brew": "麒麟一番搾啤酒",
    "knight": "Knight啤酒",
    "kronenbourg 1664": "1664啤酒系列",
    "leffe blond": "Leffe啤酒",
    "little creatures": "Little Creatures啤酒系列",
    "murphy s stout": "麥菲士愛爾蘭黑啤",
    "orion draft": "Orion啤酒",
    "paulaner": "保拉納小麥啤酒系列",
    "peroni": "Peroni啤酒",
    "san miguel": "生力啤酒",
    "san miguel blanca": "生力白啤",
    "san miguel light": "生力清啤",
    "san miguel pale pilsen": "查無資料21",
    "san miguel philippines": "生力菲律賓樽裝啤酒",
    "sapporo": "三寶樂啤酒",
    "sapporo hokkaido": "札幌啤酒系列",
    "singha": "勁獅啤酒",
    "skol": "獅威啤酒",
    "skol refreshing": "獅威啤酒",
    "snow": "雪花勇闖天涯啤酒",
    "sonderberg": "森堡啤酒",
    "stella artois": "Stella Artois啤酒系列",
    "suntory premium malt": "三得利頂級啤酒",
    "gold medal taiwan beer": "金牌台灣啤酒",
    "taiwan beer fruit flv":"台灣啤酒水果系列",
    "taiwan beer sweet touch fruit beer":"台灣啤酒果微醺系列",
    "takaha chu hi shine muscat": "宝洒造啤酒",
    "tsing tao beer": "青島啤酒",
    "tsing tao king beer":"青島巨罐裝啤酒",
    "carlsberg smooth draft":"嘉士伯醇滑啤酒",
    "tsing tao draft": "青島純生啤酒",
    "tsing tao lager": "查無資料34",
    "tsing tao lemon pilsner non alcoholic": "青島零度檸檬啤酒",
    "tsing tao light": "青島清啤",
    "tsing tao pure draft": "查無資料37",
    "tsing tao snake": "青島蛇年啤酒(限量版)",
    "tsing tao stout": "青島黑啤",
    "tsing tao wheat": "青島白啤",
    "tsing tao zero": "青島零度啤酒",
    "wusu": "烏蘇啤酒",
    "young masterclass": "少爺啤酒系列",
    "yebisu": "惠比壽啤酒",
    "yanjing draft":"燕京啤酒"
    
  ],
  "紅酒": [
    "19 crimes": "19 Crimes紅酒系列",
    "abtei himmerod": "Abtei Himmerod紅酒系列",
    "allees cante haut": "Allees Cante Haut紅酒系列",
    "anakena nuna": "Anakena Nuna紅酒系列",
    "aney haut": "Aney Haut紅酒系列",
    "antu": "Antu紅酒系列",
    "apothic": "Apothic紅酒系列",
    "arrogant frog": "Arrogant Frog紅酒系列",
    "avamposti piemonte": "Avamposti Piemonte紅酒系列",
    "b père r mouton cadet rouge 12 x 750ml": "B Père R Mouton Cadet Rouge 12 X 750Ml紅酒系列",
    "babich winemakers": "Babich Winemakers紅酒系列",
    "banrock station": "Banrock Station紅酒系列",
    "barefoot": "Barefoot紅酒系列",
    "baron": "Baron紅酒系列",
    "beefsteak club": "Beefsteak Club紅酒系列",
    "beefsteakclub": "Beefsteakclub紅酒系列",
    "beringer founders": "Beringer Founders紅酒系列",
    "bodega norton 1895 coleccion": "Bodega Norton 1895 Coleccion紅酒系列",
    "bodegas riojanas": "Bodegas Riojanas紅酒系列",
    "bonpas": "Bonpas紅酒系列",
    "calvet": "Calvet紅酒系列",
    "campo viejo": "Campo Viejo紅酒系列",
    "cape": "Cape紅酒系列",
    "carlo rossi": "Carlo Rossi紅酒系列",
    "carnivor": "Carnivor紅酒系列",
    "cartillon haut": "Cartillon Haut紅酒系列",
    "castelmaure corbieres": "Castelmaure Corbieres紅酒系列",
    "castillo albai": "Castillo Albai紅酒系列",
    "cel des": "Cel Des紅酒系列",
    "chap moines saint": "Chap Moines Saint紅酒系列",
    "chapel hill the parson": "Chapel Hill The Parson紅酒系列",
    "chateau": "Chateau紅酒系列",
    "chemin des papes": "Chemin Des Papes紅酒系列",
    "château": "Château紅酒系列",
    "circumference napa valley": "Circumference Napa Valley紅酒系列",
    "clarendelle": "Clarendelle紅酒系列",
    "clos dominique cuvée autrement": "Clos Dominique Cuvée Autrement紅酒系列",
    "con de oriza ribera del duero": "Con De Oriza Ribera Del Duero紅酒系列",
    "concha y": "Concha Y紅酒系列",
    "confidences de": "Confidences De紅酒系列",
    "cono sur": "Cono Sur紅酒系列",
    "cote mas": "Cote Mas紅酒系列",
    "croix montlabert saint": "Croix Montlabert Saint紅酒系列",
    "darcins haut": "Darcins Haut紅酒系列",
    "dark horse california": "Dark Horse California紅酒系列",
    "dbr lafite": "Dbr Lafite紅酒系列",
    "de bortoli noble one bot semil 375ml": "De Bortoli Noble One Bot Semil 375Ml紅酒系列",
    "dom daussieres altan daussieres": "Dom Daussieres Altan Daussieres紅酒系列",
    "don luciano": "Don Luciano紅酒系列",
    "e guigal": "E Guigal紅酒系列",
    "edmond de rothschild croix des laurets": "Edmond De Rothschild Croix Des Laurets紅酒系列",
    "emalee": "Emalee紅酒系列",
    "fam lapalu": "Fam Lapalu紅酒系列",
    "frank family": "Frank Family紅酒系列",
    "franzia": "Franzia紅酒系列",
    "french cellars": "French Cellars紅酒系列",
    "frescobaldi tenuta di castiglioni": "Frescobaldi Tenuta Di Castiglioni紅酒系列",
    "genestras": "Genestras紅酒系列",
    "george wyndham": "George Wyndham紅酒系列",
    "gerard bertrand": "Gerard Bertrand紅酒系列",
    "grant burge": "Grant Burge紅酒系列",
    "h faugeres saint": "H Faugeres Saint紅酒系列",
    "hahn": "Hahn紅酒系列",
    "hahn slh": "Hahn Slh紅酒系列",
    "hardys": "Hardys紅酒系列",
    "ht branaire ducru haut": "Ht Branaire Ducru Haut紅酒系列",
    "jacobs creek": "Jacobs Creek紅酒系列",
    "jalousie beaulieu château jalousie beaulieu": "Jalousie Beaulieu Château Jalousie Beaulieu紅酒系列",
    "jean bouchard": "Jean Bouchard紅酒系列",
    "jj mcwilliam": "Jj Mcwilliam紅酒系列",
    "jp chenet vdp doc": "Jp Chenet Vdp Doc紅酒系列",
    "k": "K紅酒系列",
    "kaiken by montes": "Kaiken By Montes紅酒系列",
    "kangaroo ridge": "Kangaroo Ridge紅酒系列",
    "kendall jackson": "Kendall Jackson紅酒系列",
    "koyle": "Koyle紅酒系列",
    "koyle royale": "Koyle Royale紅酒系列",
    "la": "La紅酒系列",
    "la roche": "La Roche紅酒系列",
    "lafite": "Lafite紅酒系列",
    "le haut médoc dissan 2016 750ml": "Le Haut Médoc Dissan 2016 750Ml紅酒系列",
    "legende": "Legende紅酒系列",
    "les": "Les紅酒系列",
    "lescalle": "Lescalle紅酒系列",
    "leydet valen saint": "Leydet Valen Saint紅酒系列",
    "lindemans cawarra": "Lindemans Cawarra紅酒系列",
    "little giant": "Little Giant紅酒系列",
    "locations e spanish": "Locations E Spanish紅酒系列",
    "los vascos": "Los Vascos紅酒系列",
    "louis latour côte de beaune villages 750ml": "Louis Latour Côte De Beaune Villages 750Ml紅酒系列",
    "m cellars": "M Cellars紅酒系列",
    "mabalel": "Mabalel紅酒系列",
    "maison castel": "Maison Castel紅酒系列",
    "marjosse": "Marjosse紅酒系列",
    "marques de": "Marques De紅酒系列",
    "matua marlborough": "Matua Marlborough紅酒系列",
    "mcguigan black label": "Mcguigan Black Label紅酒系列",
    "michel lynch nature rouge": "Michel Lynch Nature Rouge紅酒系列",
    "mission est hawkes bay": "Mission Est Hawkes Bay紅酒系列",
    "mont": "Mont紅酒系列",
    "montes": "Montes紅酒系列",
    "motif": "Motif紅酒系列",
    "moulin dissan md": "Moulin Dissan Md紅酒系列",
    "mount peak": "Mount Peak紅酒系列",
    "mouton cadet": "Mouton Cadet紅酒系列",
    "mucho más": "Mucho Más紅酒系列",
    "mud": "Mud紅酒系列",
    "ox hardy mclaren vale grenach 750ml": "Ox Hardy Mclaren Vale Grenach 750Ml紅酒系列",
    "oyster bay": "Oyster Bay紅酒系列",
    "paloumey ailes de paloumey haut": "Paloumey Ailes De Paloumey Haut紅酒系列",
    "penfolds": "Penfolds紅酒系列",
    "pensees tour carnet haut": "Pensees Tour Carnet Haut紅酒系列",
    "petaluma yellow": "Petaluma Yellow紅酒系列",
    "peter max": "Peter Max紅酒系列",
    "petit": "Petit紅酒系列",
    "pio cesare": "Pio Cesare紅酒系列",
    "raimat": "Raimat紅酒系列",
    "rambeau lussac saint": "Rambeau Lussac Saint紅酒系列",
    "rauzan gassies haut": "Rauzan Gassies Haut紅酒系列",
    "rawson retreat": "Rawson Retreat紅酒系列",
    "rawsons retreat": "Rawsons Retreat紅酒系列",
    "ricossa": "Ricossa紅酒系列",
    "riedel o to go": "Riedel O To Go紅酒系列",
    "rupert & rothschild rupert & rothschild classique": "Rupert & Rothschild Rupert & Rothschild Classique紅酒系列",
    "saga": "Saga紅酒系列",
    "saint": "Saint紅酒系列",
    "santa": "Santa紅酒系列",
    "sarget de gruaud larose saint julien 750ml": "Sarget De Gruaud Larose Saint Julien 750Ml紅酒系列",
    "second camensac haut": "Second Camensac Haut紅酒系列",
    "sherwood": "Sherwood紅酒系列",
    "stanley": "Stanley紅酒系列",
    "stanley traditional": "Stanley Traditional紅酒系列",
    "substance": "Substance紅酒系列",
    "suntory antioxidant additive free": "Suntory Antioxidant Additive Free紅酒系列",
    "terr baume": "Terr Baume紅酒系列",
    "terra vega": "Terra Vega紅酒系列",
    "terrunyo": "Terrunyo紅酒系列",
    "tessellae old vines": "Tessellae Old Vines紅酒系列",
    "the": "The紅酒系列",
    "tierra de": "Tierra De紅酒系列",
    "tilia": "Tilia紅酒系列",
    "tommasi": "Tommasi紅酒系列",
    "torres sangres de toro": "Torres Sangres De Toro紅酒系列",
    "tread softly": "Tread Softly紅酒系列",
    "trocard": "Trocard紅酒系列",
    "unknown": "Unknown紅酒系列",
    "vieux château": "Vieux Château紅酒系列",
    "vina": "Vina紅酒系列",
    "waitrose": "Waitrose紅酒系列",
    "whistler barossa": "Whistler Barossa紅酒系列",
    "wolf blass": "Wolf Blass紅酒系列",
    "wynns": "Wynns紅酒系列",
    "yalumba": "Yalumba紅酒系列",
    "yellow tail": "Yellow Tail紅酒系列"
  ],

]
