//
//  CategoryNormChinese.swift
//  Supermarket
//
//  Created by cheung gary on 5/5/2025.
//


import Foundation

/// “水果” 子分類下的 norm → 中文 映射
let subCategoryNormToChinese: [String: [String: String]] = [
  "水果": [
    "apple":        "蘋果",
    "avocado":      "牛油果",
    "banana":       "香蕉",
    "blackberry":   "黑莓",
    "blueberry":    "藍莓",
    "calamansi":    "金橘",
    "cherry tomato":"櫻桃小番茄",
    "coconut":      "椰子",
    "dragon fruit": "火龍果",
    "durian":       "榴槤",
    "grape":        "葡萄",
    "grapefruit":   "葡萄柚",
    "kiwi":         "奇異果",
    "lemon":        "檸檬",
    "longan":       "龍眼",
    "mandarin":     "橘子",
    "orange":       "橙",
    "pear":         "梨",
    "pineapple":    "菠蘿",
    "pomelo":       "柚子",
    "raspberry":    "樹莓",
    "strawberry":   "士多啤梨",
    "sun plum":     "太陽李",
    "tomato":       "番茄",
    "watermelon/hamimelon/papaya/melon":   "西瓜,木瓜,哈密瓜,香瓜",
    "others":       "其他",
    "mango":       "芒果"
  ],
  "蔬菜": [
    "mushroom":                      "蘑菇",//
    "sweet potato":                  "番薯",//
    "bell pepper":                   "甜椒",//
    "cherry tomatoes":               "車厘茄",//
    "potato":                        "薯仔",//
    "sweet bean":                    "四季豆",
    "tomatoes":                      "番茄",//
    "springonion/ginger/garlic":    "蔥薑蒜",//
    "herbs":                         "香草",//
    "choi sum":                      "菜心",//
    "cucumber":                      "黃瓜",//
    "lettuce":                       "生菜",
    "onion":                         "洋蔥",//
    "pumpkin":                       "南瓜",//
    "asparagus":                     "蘆筍",//
    "broccolini":                    "西蘭花",//
    "cabbage":                       "高麗菜",
    "others":                        "其他",
    "carrot":                         "紅蘿蔔/甘筍",//
    "corn":                           "栗米",//
    "pak choi":                       "小白菜",
    "pak choy":                       "小白菜",    
    "spinach":                        "菠菜",//
    "baby corn":                      "栗米筍",//
    "bean sprout":                    "豆芽",//
    "cauliflower":                    "椰菜花",
    "celery":                         "西芹",//
    "chinese lettuce":                "唐生菜",
    "eggplant":                       "茄子",//
    "green hydro":                    "水培蔬菜",
    "indian lettuce":                 "油麥菜",//
    "okra":                           "秋葵",//
    "radish":                         "白蘿蔔",
    "salad mix":                      "沙律菜",//
    "zucchini":                       "翠玉瓜",//
    "a vegetable sprout":             "菜苗",//
    "bamboo shoots":                  "竹筍",//
    "buddhism melon":                 "佛手瓜",//
    "celtuce":                        "萵筍",//
    "chinese kale":                   "芥蘭",//
    "round cabbage":                 "椰菜",
    "wong choi":                 "旺菜",//
    "kale":                 "羽衣甘藍",//
  ],
  
    "汽水": [
      "7 up free soft drink":                        "七喜輕怡汽水",
      "7 up soft drink":                             "七喜汽水",
      "barebells barebells rtd high protein milkshake 330ml - chocolate": "Barebells高蛋白奶昔",
      "BUNDABERG":                                   "賓得寶",
      "CALPIS Calpis Soda":                          "可爾必思",
      "casino delices traditional lemonade delices": "Casino Delices",
      "celsius celsius® fitness drink 325ml":        "Celsius® 健身飲料",
      "coca-cola bottle":                            "可口可樂（瓶裝）",
      "coca-cola can":                               "可口可樂（罐裝）",
      "coca-cola lemon":                             "可口可樂檸檬味",
      "coca-cola plus":                              "可口可樂 Plus",
      "coca-cola zero bottle":                       "可口可樂Zero（瓶裝）",
      "coca-cola zero can":                          "可口可樂Zero（罐裝）",
      "crystal spring":                              "碧泉",
      "dash sparkling mango 330 ml":                 "Dash 氣泡水",
      "efferve drink":                               "Efferve ",
      "ESSENTIAL WAITROSE":                          "Essential Waitrose ",
      "evian sparkling":                             "依雲氣泡水",
      "famous soda":                                 "Famous Soda",
      "fanta grape flavoured soda":                  "芬達葡萄味汽水",
      "fanta orange flavoured soda":                 "芬達橙味汽水",
      "monster energy drink":                        "魔爪能量飲料",
      "monster ultra energy drink":                  "魔爪 Ultra 能量飲料",
      "nocco nocco lemon":                           "NOCCO",
      "okf sparkling":                               "OKF 氣泡水",
      "on gold stand. protein shake chocolate":      "ON Gold Standard",
      "ooha sparkling":                              "OOHA 氣泡水",
      "pepsi cola":                                  "百事可樂",
      "pepsi cola No Sugar":                         "百事可樂無糖",
      "perrier magnetice":                           "法國巴黎果味礦泉水",
      "pocari ion supply drink":                     "寶礦力水特",
      "pokka sapporo drink":                         "Pokka Sapporo",
      "red bull energy drink":                       "紅牛能量飲料",
      "remedy kombucha":                             "Remedy 康普茶",
      "ribena lightly sparkling":                    "Ribena 淡味氣泡水",
      "ribena sparkling blackcurrant drink can case 24 x 320ml": "利賓納",
      "saitou drink":                        "Saitou 飲料",
      "san benedetto spark.mineral water 1.5l":      "聖碧濤 氣泡礦泉水",
      "Meadows Sparkling":                           "Meadows 氣泡水",
      "Meadows Soda Water":                          "Meadows 梳打水",
      "meadows cola":                                "Meadows 可樂",
      "SANGARIA":                                    "新加利亞汽水",
      "sarsae sparkling sarsa drink":                "沙示汽水",
      "schweppes ginger beer":                      "玉泉薑汁啤酒",
      "schweppes soda other flv":                    "玉泉其他口味汽水",
      "schweppes soda Lemonade":                     "玉泉檸檬口味梳打水",
      "schweppes soda":                              "玉泉蘇打水",
      "schweppes cream soda":                        "玉泉忌廉汽水",
      "Schweppes tonic water":                       "玉泉湯力水",
      "schweppes +c lemon flavoured soda":           "玉泉+C檸檬梳打",
      "Schweppes Dry Ginger":                        "玉泉乾薑啤",
      "CHI FOREST Sparkling Water":                  "元氣森林",
      "suntory c.c. lemon":                          "三得利 C.C",
      "sunkist sparkling lemonade":                  "新奇士 有氣檸檬汁",
      "vita Sparking":                               "維他™氣泡檸檬茶",
      "waitrose lemonade with juice":                "Waitrose",
      "Watson soda":                                 "屈臣氏梳打水",
      "Watson tonic water":                          "屈臣氏湯力水",
      "Woolworths Soda Wate":                        "Woolworths 梳打水",
      "Woolworths Tonic Water":                      "Woolworths 湯力水",
      "CHANG Soda":                                  "泰象啤",
      "EVERVESS Evervess Soda":                      "依維世梳打水",
      "fentimans rose lemonade":                     "Fentimans 玫瑰檸檬水",
      "Fever Tree tonic water":                      "熱樹湯力水",
      "SAN PELLEGRINO Sparkling":                    "聖培露有氣礦泉水",
      "Perrier Sparkling":                           "法國巴黎礦泉水",
      "known stranger sparkling":                    "益生元氣有氣果汁",
      "libogen drink":                               "力保健"
    
    ],
    
      "即飲茶類、咖啡、奶茶": [
        "authentic tea house taiwan jing-xuan oolongtea": "淳茶舍冷萃台灣金萱烏龍茶",
        "c'estbon black tea original tea": "怡寶佐味茶事紅茶原味茶飲料",
        "c'estbon chrysanthemum tea": "怡寶菊花茶原味茶飲料",
        "c'estbon lemon tea": "怡寶至本清潤檸檬茶",
        "c'estbon oolong tea original tea": "怡寶烏龍茶",
        "cha xiao kai tea drinks": "茶小開茶飲",
        "chai li won sugarfree tea": "茶裏王無糖日式綠茶",
        "crystal spring green tea drink": "晶泉綠茶飲料",
        "dai pai dong lemon tea": "大排檔港式檸檬茶",
        "dydo leaf green tea": "大島茶葉綠茶",
        "four seas lemon tea": "四洲檸檬茶",
        "haruna produce haruna the honey black tea": "Haruna Produce蜂蜜紅茶",
        "haruna produce lucafe houjicha": "Haruna Produce Lucafe焙茶",
        "healthworks drink": "健康工房飲品",
        "hi-c ceylon lemon tea": "陽光錫蘭檸檬茶",
        "hi-c chrysanthemum tea": "陽光菊花茶",
        "hi-c lychee honey tea": "陽光荔枝蜜茶",
        "hi-c mandarin tea": "陽光橘子茶",
        "hoi tin tong herbs tea": "海天堂草本茶",
        "hung fook tong drink": "鴻福堂鮮製飲品",
        "inabaen black oolong tea": "稻葉園黑烏龍茶",
        "itikoen tea": "伊藤園茶飲",
        "jia duo bao herbal tea": "加多寶涼茶",
        "kirin afternoon lemon tea": "麒麟午後紅茶檸檬紅茶",
        "kirin afternoon tea lemon": "麒麟午後紅茶檸檬紅茶",
        "kirin afternoon tea straight": "麒麟午後紅茶原味",
        "kirin rich green tea": "麒麟生茶",
        "kochakaden craftea lemon tea": "紅茶花伝CRAFTÉA檸檬紅茶",
        "kochakaden craftea orange black case": "紅茶花伝CRAFTÉA橙茶飲料",
        "kochakaden craftea peach tea": "紅茶花伝CRAFTÉA蜜桃茶",
        "lotte tea": "樂天初飲初樂",
        "meadows dahongpao oolong tea": "Meadows大紅袍烏龍茶",
        "meadows grosvenor momordica": "Meadows羅漢果茶",
        "meadows imperatae cane drink": "Meadows竹蔗茅根飲品",
        "meadows jasmine tea": "Meadows茉莉花茶",
        "meko passion fruit and orange fruit tea": "MEKO聯乘水果茶",
        "mr. kon ice tea": "康師傅冰紅茶",
        "mzk life honey sugar fig tea": "花研草說無花蜂糖潤咳茶",
        "mzk life osmanthus & snow pear tea": "花研草說桂花雪梨潤肺茶",
        "nongfu spring oriental leaf": "農夫山泉東方樹葉茶飲",
        "nongfu spring tea pi tea": "農夫山泉茶π茶飲",
        "original taste drink": "原味家作飲品",
        "original taste chrysanthemum w honey": "原味本舖蜂蜜菊花茶",
        "original taste fig apple & pear": "無花果蘋果雪梨茶",
        "original taste pear sichuan loquat": "鮮枇杷雪梨茶",
        "pura blended oolong tea": "PURA綜合烏龍茶",
        "pure life hk leys tea": "PURELIFEHKLeysTea",
        "rikyu chasaku honey green tea": "利休茶作蜂蜜綠茶",
        "rikyu chasaku japanese style sencha tea": "利休茶作日式煎茶",
        "robiff oolong tea": "津路烏龍茶",
        "robiff → oolong tea": "津路烏龍茶",
        "royal t garden premium oolong tea beverage": "御茶園冷山茶王烏龍茶飲品",
        "ruhn chan herbal tea": "清潤涼茶",
        "sensa cools herbal": "清熱酷飲品",
        "suntory iyemon green tea": "伊右衛門綠茶",
        "suntory jasmine oolong tea": "三得利茉莉烏龍茶",
        "suntory oolong tea": "三得利烏龍茶",
        "tao ti apple green tea": "道地蘋果綠茶",
        "tao ti green tea (honey)": "道地蜂蜜綠茶",
        "tao ti honey green tea": "道地蜂蜜綠茶",
        "tao ti kyoho grape black tea": "道地巨峰葡萄紅茶",
        "tao ti lemon black tea": "道地檸檬紅茶",
        "tao ti lemon with honey green tea": "道地檸檬(蜂蜜)綠茶",
        "tao ti lychee black tea": "道地荔枝紅茶",
        "tao ti mandarin green tea": "道地蜂蜜柑桔綠茶",
        "tao ti mandarin lemon": "道地百果園柑桔檸檬微碳酸",
        "tao ti orange flavour black tea": "道地橙紅茶",
        "tao ti pineapple green tea": "道地菠蘿綠茶",
        "tao ti sup oolong tea": "道地極品烏龍茶",
        "tao ti supreme chrysanthemum oolong tea": "道地極品菊花烏龍茶",
        "tao ti supreme genmaicha": "道地極品玄米茶",
        "tao ti supreme light barley tea": "道地極品清。麥茶",
        "vita cold brew no sugar puerh tea drink": "維他無糖冷泡茶高山普洱",
        "vita cold brew no sugar tie guan yin": "維他無糖冷泡茶鐵觀音",
        "vita gor yin hai icy pink grapefruit tea": "維他菓然系冰震紅西柚茶",
        "vita honey chrysanthemum tea": "維他蜜糖菊花茶",
        "vita honey lemon tea": "維他蜂蜜檸檬茶",
        "vita lemon tea": "維他檸檬茶",
        "vita lime lemon tea": "維他青檸檸檬茶",
        "vita low sugar tea": "維他低糖檸檬茶",
        "vita supericy lemon tea": "維他SUPERICY檸檬茶",
        "yushan double leaf lemon tea": "御山雙葉檸檬茶",
        "boss coffee": "BOSS黑咖啡",
        "dai pai dong hk style coffee": "大排檔港式咖啡",
        "escafe smoovlatte hazelnut flavour coffee": "雀巢咖啡Smoovlatte榛子味咖啡",
        "nescafe cafe latte aluminum": "雀巢拿鐵",
        "nescafe coffee": "NESCAFÉ咖啡",
        "nescafe nescafe coconut americano": "雀巢椰青美式咖啡",
        "nescafe nescafe coconut latte": "雀巢絲滑椰奶咖啡",
        "nescafe nescafe milk & sugar coffee": "雀巢香滑咖啡",
        "nescafe americano coffee": "雀巢美式咖啡",
        "nescafe nanyang white coffee": "雀巢南洋白咖啡",
        "nescafe smoovlatte mocha": "雀巢絲滑朱古力味咖啡",
        "suntory premium boss black coffee": "Suntory Boss高級無糖黑咖啡",
        "ucc coffee": "UCC咖啡",
        "asahi wonda coffee": "朝日Asahi Wonda咖啡",
        "boss coffee latte": "BOSS拿鐵",
        "dai pai dong coffee": "大排檔港式咖啡",
        "doutor hinokiwami black sugar free coffee": "Doutor黑咖啡",
        "dydo barista's choice low sugar coffee": "大德微糖世界咖啡",
        "four seas premium coffee": "四洲香濃咖啡",
        "georgia coffee": "喬治亞咖啡",
        "kirin fire one day coffee": "麒麟FireOneDay直火黑咖啡",
        "kirin fire one day unsweetened latte": "麒麟FireOneDay無糖拿鐵",
        "mr brown blue mountain coffee": "伯朗藍山風味咖啡",
        "mr. brown black coffee": "伯朗醇黑咖啡",
        "mr. brown deluxe coffee": "伯朗經典咖啡",
        "nescafe extra shot coffee": "NESCAFÉ特濃即飲咖啡",
        "nescafe full roast coffee": "NESCAFÉ醇釀烘焙咖啡",
        "nescafe instant coffee drink": "NESCAFÉ即溶咖啡飲品",
        "nescafe korean cafe collection cafe latte": "NESCAFÉ韓系拿鐵咖啡",
        "nescafe korean cafe collection cold brew black coffee": "NESCAFÉ韓系冷萃黑咖啡",
        "nescafe rich coffee": "NESCAFÉ香濃咖啡",
        "nescafe smoovlatte": "NESCAFÉ絲滑拿鐵",
        "nescafe smoovlatte hazelnut coffee": "NESCAFÉ絲滑榛子拿鐵",
        "okf coffee": "OKF咖啡",
        "pokka premium milk coffee": "PokkaPremium牛奶咖啡",
        "sangaria coffee": "新加利亞咖啡",
        "starbucks coffee": "Starbucks咖啡飲品",
        "suntory craft boss black coffee": "SUNTORYCraftBoss無糖黑咖啡",
        "suntory craft boss cafe mocha": "SUNTORYCraftBoss摩卡咖啡",
        "suntory double impact less sgr coffee": "SUNTORYDoubleImpact低糖咖啡",
        "itoen green tea": "伊藤園綠茶",
        "itoen green tea w/ roasted rice tea": "伊藤園玄米茶",
        "itoen jasmine tea": "伊藤園茉莉綠茶",
        "itoen oi ocha genmaicha": "伊藤園玄米茶",
        "kochakaden craftea orange black tea": "紅茶花伝CRAFTÉA橙味紅茶",
        "kochakaden craftea peach tea beverage": "紅茶花伝CRAFTÉA蜜桃茶飲",
        "nescafe cold brew black aluminum": "雀巢冷萃無糖黑咖啡",
        "ruhn chan chrysanthemum tea": "潤湛菊花茶",
        "ruhn chan red date tea": "潤湛紅棗茶",
        "ruhn chan water chestnut & sugar cane": "潤湛馬蹄蔗水",
        "sangaria anatano ocha": "新加利亞抹茶",
        "vita hk style milk tea": "維他港式奶茶",
        "black & white classic milk tea": "黑白經典奶茶",
        "if thai milk tea": "IF泰式奶茶",
        "kam cha hk style milk tea": "金茶王港式奶茶",
        "meadows milk tea": "Meadows原味奶茶",
        "tai hing hk style milk tea": "太興港式奶茶",
        "tao ti supreme oolong milk tea": "道地極品烏龍奶茶",
        "uni president milk tea": "統一奶茶",
        "tao ti supreme meta slim tea": "道地極品纖解茶",
        "tao ti supreme oolong": "道地極品烏龍茶",
        "vita cold brew no sugar jasmine tea": "維他冷泡無糖香片茶",
        "authentic tea house oolong tea": "淳茶舍大紅袍烏龍茶",
        "tao ti supreme meta green tea": "道地極品解綠茶",
        "tao ti supreme meta tea": "道地極品解茶",
        "vita chrysanthemum tea": "維他菊花茶",
        "itoen tea":"伊藤園茶飲",
        "vita ceylon lemon tea": "維他錫蘭檸檬茶",
        "vita ya shi xiang lemon tea": "維他鴨屎香檸檬茶",
        "vita zero sugar lemon tea": "維他零糖檸檬茶",
        "nestea ice rush lemon tea": "雀巢冰極檸檬茶",
        "nestea lemon tea": "雀巢檸檬茶",
        "vita cold brew no sugar pure tea": "維他冷泡無糖高山普洱茶",
        "authentic tea house cloudy green tea": "淳茶舍雲抹日式綠茶",
        "authentic tea house jasmine green tea": "淳茶舍茉莉綠茶",
        "authentic tea house yinhao jasmine green tea": "淳茶舍銀毫茉莉綠茶",
        "vita cold brew no sugar puer tea": "維他冷泡無糖高山普洱茶",
        "vita cold brew no sugar ceylon lemon tea": "維他冷泡無糖鍚蘭檸檬茶",
        "vita cold brew no sugar oolong tea": "維他冷泡無糖烏龍茶",
        "vita low sugar chrysanthemum": "維他低糖菊花茶",
        "authentic tea house gyokuro green tea": "淳茶舍無糖玉露綠茶",
        "authentic tea house puer tea": "淳茶舍消茶普洱茶",
        "nestea honey pear tea": "雀巢蜂蜜雪梨茶",
        "tao ti supreme meta oolong tea": "道地極品纖解烏龍茶",
        "tao ti supreme osmanthus green tea": "道地極品桂花綠茶",
        "tao ti supreme tangerine peel tea": "道地極品橘皮香茶",
        "vita apple green tea": "維他蘋果綠茶",
        "vita gor yin hai icy peach tea": "維他菓然系冰震蜜桃茶",
        "vita lemon tea low sugar": "維他低糖檸檬茶",
        "vita gor yin hai apple & mango tea": "維他菓然系蘋果芒果茶",
        "authentic tea house cold brew green tea": "淳茶舍冷萃日式深蒸綠茶",
        "dai pai dong hk style milk tea": "大排檔港式奶茶",
        "kirin afternoon milk tea": "麒麟午後奶茶",
        "rikyu chasaku tea": "利休茶作茶飲",
        "vita apple jasmine": "維他清心棧飲品",
        "tao ti supreme light oolong tea": "道地極品清烏龍茶",
        "vita fresh lemon tea": "維他新鮮茶飲",
        "vita lemon tea sparkling zero sugar": "維他零糖氣泡檸檬茶",
        "vita lemon tea zero sugar": "維他零糖檸檬茶",
        "tao ti yashi xiang lemon tea": "道地鴨屎香茶飲",
        "vita cold brew no sugar dong ding ooling": "維他冷泡無糖凍頂烏龍茶",
        "vita gor yin hai icy lemon tea": "維他菓然系冰震檸檬茶",
        "vita japanese style peach tea": "維他日式蜜桃茶",
        "itamachi barley tea": "板町麥茶",
        
    
      ],
  
  "奶類、乳酪飲品": [
    "aboutea gold oolong milk tea": "盛致黃金烏龍奶茶",
    "anchor full cream uht milk": "安佳全脂牛奶",
    "anlene hi-cal low fat milk": "安怡高鈣低脂奶",
    "aus'mania milk": "Aus'Mania牛奶系列",
    "benecol original yogurt drink": "倍樂醇原味乳酪飲品",
    "binggrae flavoured milk": "Binggrae牛奶飲品系列",
    "black & gold full cream uht milk": "Black & Gold 全脂牛奶",
    "casino organic plain rice drink": "Casino有機米類飲品",
    "cheer organic fresh milk": "滋味有機鮮奶",
    "cow & gate milk": "牛欄 Milk Plus 兒童奶",
    "daioni organic milk": "Daioni 有機牛奶系列",
    "dairy kirishima milk": "霧島山麓全脂牛奶",
    "devondale milk": "澳洲德運牛奶系列",
    "dutch lady chocolate milk": "子母牌巧克力牛奶",
    "dutch lady milk": "子母牌牛奶系列",
    "dutch lday yogurt": "子母牌優格飲飲品",
    "emmi semi skimmed milk": "Emmi 半脫脂牛奶",
    "fred & chloe milk": "Fred & Chloe牛奶系列",
    "freshjoy fresh milk": "悅鮮活鮮牛奶",
    "harvey fresh milk": "澳洲哈維牛奶系列",
    "just pure drinking yoghurt": "純甄優格飲品系列",
    "kokuaji 3.6 fresh milk": "北海道特選3.6牛乳",
    "kowloon dairy soya milk drink": "維記豆奶系列",
    "kowloon dairy milk": "維記牛奶系列",
    "kowloon dairy yogurt": "維記乳酪飲品系列",
    "lactel uht semi skimmed milk": "Lactel UHT 半脫脂牛奶?",
    "macro organic milk": "Macro 有機奶系列",
    "meadow milk": "Meadow牛奶系列",
    "meiji milk": "明治牛奶系列",
    "mengniu low fat high calcium milk": "蒙牛低脂高鈣牛奶",
    "monmilk chewy milk beverage": "蒙牛真果粒",
    "nestle milk": "雀巢牛奶系列",
    "ovaltine rich chocolate malted milk": "阿華田濃滑朱古力麥芽奶",
    "pauls milk": "Pauls牛奶系列",
    "daioni organic semi skimmed milk": "Daioni 有機半脫脂牛奶",
    "pure organic rice milk": "Pure Harvest 有機米奶",
    "shiny milk": "每日鮮語牛奶系列",
    "soymilk": "豆漿",
    "the bridge bio rice drink": "The Bridge 有機米飲",
    "trappist dairy milk": "十字牌牛奶系列",
    "vita milk": "維他牛奶系列",
    "vitasoy australia soy milk": "維他奶 Australia 原味豆奶",
    "vitasoy calci plus drink": "維他鈣思寶豆奶系列",
    "vitasoy australia milk": "維他澳洲奶制品系列",
    "vitasoy bean milk": "維他奶豆奶系列",
    "vitasoy vita yoghurt flavor drink": "維他奶乳酪飲",
    "want want lactic acid drink": "旺仔乳酸飲品",
    "emmi premium milk": "伊美瑞士特級牛奶"
  ],
  "沖調飲品": [
    "ace sencha tea bag": "Ace 煎茶茶包",
    "ah huat extra rich": "亞發特濃白咖啡",
    "ah huat roast coffee": "亞發炭燒白咖啡",
    "ah huat white coffee": "亞發白咖啡",
    "ahmad fruit tea": "Ahmad Tea 水果茶",
    "authentic king chrysanthemum": "Authentic King 皇菊花茶",
    "authentic king imperate cane": "Authentic King 茅根茶",
    "belmio coffee cap": "Belmio膠囊咖啡系列",
    "blackgold legacy ginger tea": "Blackgold 黑金傳奇黑糖薑茶",
    "bob's red mill flaxseed meal": "Bob’s Red Mill 亞麻籽粉",
    "borbone nespresso coffee capsule": "Borbone 膠囊咖啡",
    "brooke bond pg tips tea": "PG Tips 茶包",
    "cafedirect roast coffee": "Café Direct 烘焙咖啡",
    "camellia treasure tea": "Camellia Treasure茶包系列",
    "casino coffee": "Casino咖啡粉/朱古力粉系列",
    "catalo drink": "Catalo飲品系列",
    "catalo oat milk": "Catalo燕麥奶系列",
    "celestial tea": "Celestial茶包系列",
    "chef kim honey citron tea": "金師傅蘆薈柚子茶",
    "chek hup coffee": "澤合咖啡系列",
    "clipper tea": "金舶英茶(英國)茶包系列",
    "costa coffee signature": "Costa Coffee 招牌咖啡",
    "coudo ginger tea": "Coudo 薑茶",
    "coudo honey citron tea": "高島蜂蜜柚子茶",
    "dai pai dong yuan yang": "大排檔鴛鴦系列",
    "dai pai dong milk tea powder": "大排檔奶茶系列",
    "dai pai dong coffee": "大排檔咖啡系列",
    "dai pai dong tea": "大排檔茶包系列",
    "dai pai dong drink": "大排檔即溶飲品系列",
    "daisho green veg drink": "Daisho 綠色蔬菜飲品",
    "damtuh ginger tea": "丹特薑茶",
    "dextro detrox d.glucose powder": "得力素能量葡萄糖粉",
    "dilmah earl grey tea": "迪爾瑪伯爵茶",
    "ediya coffee": "Ediya咖啡系列",
    "emerail tea": "貴茶茶包系列",
    "essential waitrose coffee": "Essential Waitrose咖啡系列",
    "food nation ginger tea": "Food Nation 薑茶",
    "g7 coffee": "G7咖啡系列",
    "gingen ginger tea": "真精薑茶系列",
    "golden swallow drink": "金燕子即沖飲品系列",
    "good day mocacinno 3in1": "Good Day 摩卡三合一咖啡",
    "green dot dot 100%": "綠點點即沖系列",
    "green dot dot soya milk": "綠點點豆奶系列",
    "greenmax black sesame meal": "綠源黑芝麻糊",
    "healthy green corn mustard": "健康綠玉米芥末粉",
    "healthy green sugar cane": "健康綠甘蔗粉",
    "ho cha tea box set": "好茶養生 盒裝系列",
    "ho cha tea pack set": "好茶養生 單包裝系列",
    "horlicks drink": "好立克飲品系列",
    "illy coffee": "意利咖啡系列",
    "indocafe coffee": "迎樂咖啡系列",
    "jaf tea": "佳福茶茶包系列",
    "jomeis fine foods cacao": "Jomeis Fine Foods飲品系列",
    "kai tsun tea": "啟贊茶飲系列",
    "kam cha drink": "Kam Cha飲品系列",
    "kapal api coffee": "火船牌咖啡",
    "key coffee drip on": "Key Coffee 滴漏咖啡",
    "kim guan guan kopi-coffee": "金冠冠馬來西亞咖啡",
    "kimbo coffee": "Kimbo咖啡系列",
    "kobe haikara coffee": "神戸齋藤珈琲店咖啡",
    "lavazza coffee": "Lavazza咖啡系列",
    "lipton tea bag": "立頓茶包系列",
    "lipton milk tea": "立頓奶茶系列",
    "luk yu tea bag": "陸羽茶包系列",
    "maxwell coffee": "麥斯威爾咖啡系列",
    "meadows original coffee 3in1": "Meadows 原味三合一咖啡",
    "melitta coffee": "美樂家咖啡系列",
    "milo": "美祿飲品系列",
    "mingcha tea": "明茶房茶包系列",
    "moccona coffee": "名仕咖啡系列",
    "movenpick capsules": "Mövenpick咖啡膠囊",
    "movevnpick gold original coffee": "Mövenpick咖啡",
    "mr & mrs bean": "Mr & Mrs Bean",
    "mr brown milk tea/coffee": "伯朗奶茶/咖啡",
    "mzk life tea": "花研草說茶飲系系列",
    "nanguo coconut lattle 330gm": "南國椰奶拿鐵 330克",
    "natural garden tea": "田園茶飲系列",
    "nescafe 1+1 unsweet coffe": "雀巢1+1無糖咖啡",
    "nescafe 1+2 coffee": "雀巢1+2原味咖啡",
    "nescafe 1+2 rich coffee": "雀巢1+2特濃咖啡",
    "nescafe 1+2 smooth&milk coffee": "雀巢咖啡1+2奶滑咖啡",
    "nescafe 3 in 1": "雀巢拉咖啡",
    "nescafe cafe viet": "雀巢越南咖啡",
    "nescafe classic coffee": "雀巢經典咖啡",
    "nescafe coconut latte": "雀巢椰奶咖啡",
    "nescafe dolce gusto coffee": "雀巢Dolce Gusto咖啡膠囊",
    "nescafe gold coffee": "雀巢金牌咖啡系列",
    "nescafe instant coffee": "雀巢即溶咖啡",
    "nescafe nc foldable umbrella": "雀巢折疊傘 (促銷贈品)",
    "nescafe white coffee": "雀巢白咖啡",
    "nescafe nescafe x sho-chan": "雀巢X Sho-Chan聯名咖啡",
    "nescafe premium cappuccino": "雀巢極品泡沫咖啡",
    "nescafe premium smoovlatte": "雀巢極品絲滑牛奶咖啡",
    "nescafe rich blend coffee": "雀巢醇品咖啡",
    "nestle coffee mate": "雀巢咖啡伴侶",
    "nestle nescafe gold blend": "雀巢金牌咖啡",
    "nestle choc drink": "雀巢巧克力飲品系列",
    "nitto black tea white": "Nitto 白毫烏龍茶",
    "oatbedient oat milk drink": "Oatbedient燕麥奶粉系列",
    "oh!fresh orange black coffee": "Oh!Fresh 橙味黑咖啡",
    "old town 2in1": "舊街場2合1咖啡",
    "old town 3in1 white coffee": "舊街場3合1白咖啡",
    "old town 3in1 hazelnut coffee": "舊街場3合1白咖啡(榛果味)",
    "on kee tea": "安記茶飲系列",
    "organic garden drink": "慈康農圃飲品系列",
    "osk 3 in 1": "OSK 三合一咖啡",
    "osk tea": "OSK茶包系列",
    "ovaltine": "阿華田飲品系列",
    "po ma almond powder": "寶馬杏仁粉",
    "pumuen org roast coffee": "珈琲人掛耳咖啡",
    "resiprocate org sumatra whole": "Resiprocate有機蘇門答臘咖啡豆",
    "rickshaw chinese teabags": "車仔茶包系列",
    "robert timms coffee": "羅伯特替姆斯咖啡系列",
     "select instant coffee": "佳之選 即溶咖啡",
    "select honey tea": "佳之選蜂蜜茶飲系列",
    "select tea bag": "佳之選茶包系列",
    "select drink": "佳之選即沖飲品系列",
     "sensory zero sensory zero": "Sensory Zero德用咖啡掛耳包盒裝",
     "starbucks latte": "星巴克奶泡即溶咖啡系列",
     "starbucks cappuccino": "星巴克意大利泡沬即溶咖啡系列",
     "starbucks caramel coffee": "星巴克焦糖即溶咖啡系列",
     "starbucks by roast coffee": "星巴克 烘焙咖啡",
     "starbucks house blend": "星巴克研磨咖啡粉系列",
     "starbucks coffee caps": "星巴克咖啡粉膠囊",
     "starbucks origami caffe verona": "星巴克caffè verona掛耳式滴漏咖啡",
     "starbucks caffe mocha": "星巴克朱古力即溶咖啡",
     "starbucks cappucino 4 x": "星巴克 卡布奇諾4入裝",
     "starbucks caramel coffee by": "星巴克 焦糖咖啡",
     "starbucks caramel latte premium": "星巴克 焦糖拿鐵高級混合",
     "starbucks colombia by nespresso": "星巴克 哥倫比亞咖啡膠囊",
     "starbucks colombia by starbucks": "星巴克 哥倫比亞咖啡",
     "starbucks decaf roast coffee": "星巴克 無咖啡因烘焙咖啡",
     "starbucks espresso nespresso coffee capsule": "星巴克 濃縮咖啡膠囊",
     "starbucks espresso roast coffee": "星巴克濃縮咖啡",
     "starbucks house blend by": "星巴克 經典混合咖啡",
     "starbucks house blend ground": "星巴克 經典混合研磨咖啡",
     "starbucks house blend lungo": "星巴克 經典混合長咖啡",
     "starbucks italian roast coffee": "星巴克 意大利烘焙咖啡",
     "starbucks latte 4 x": "星巴克 拿鐵4入裝",
     "starbucks latte macchiatto by": "星巴克 拿鐵瑪奇朵",
     "starbucks matcha latte premium": "星巴克 抹茶拿鐵高級混合",
     "starbucks pike place by": "星巴克 派克市場咖啡",
     "starbucks single origin guatemala": "星巴克 瓜地馬拉單品咖啡",
     "starbucks single origin sumatra": "星巴克 蘇門答臘單品咖啡",
    "starbucks single-origin guatemala by": "星巴克瓜地馬拉單品咖啡",
    "starbucks spring roast coffee": "星巴克春季烘焙咖啡",
    "starbucks starbucks® caffè verona™": "星巴克 維羅納咖啡",
    "starbucks starbucks® caramel flavoured": "星巴克 焦糖風味咖啡",
    "starbucks starbucks® house blend": "星巴克 經典混合咖啡",
    "starbucks starbucks® matcha latte": "星巴克 抹茶拿鐵",
    "starbucks starbucks® nespresso coffee capsule": "星巴克 Nespresso 咖啡膠囊",
    "starbucks starbucks® roast coffee": "星巴克 烘焙咖啡",
    "starbucks starbucks® single origin": "星巴克 單品咖啡",
    "starbucks starbucks® sunny day": "星巴克 晴天咖啡混合",
    "starbucks starbucks® toffee nut": "星巴克 太妃堅果風味咖啡",
    "starbucks starbucks® vanilla flavoured": "星巴克 香草風味咖啡",
    "starbucks sunny day blend": "星巴克 晴天混合咖啡",
    "starbucks vanilla coffee by": "星巴克 香草咖啡",
    "starbucks® ristretto shot by": "星巴克 濃縮咖啡萃取",
    "sticksology tea": "Sticksology茶包系列",
    "sweet garden drink": "薌園飲品系列",
    "swiss miss chocolate drink": "瑞士小姐朱古力飲品系列",
    "tai luen hong kong": "大聯港式紅茶茶膽",
    "tao ti lychee black": "桃子荔枝紅茶",
    "tao ti supreme jasmine": "桃子極品茉莉花茶",
    "tarza caffe coffee": "Tarza咖啡系列",
    "taster choice coffee": "Taster's Choice咖啡系列",
    "taster choice freeze dried": "Taster's Choice 冷凍乾燥咖啡",
    "taylors tea bag": "泰勒茶包系列",
    "te@espresso tea caps": "Te@Espresso茶膠囊系列",
    "teapigs tea bag": "Teapigs茶包系列",
    "ten ren tea": "天仁茗茶茶飲系列",
    "ten ren pu-er tea": "天仁茗茶 普洱茶",
    "ten ren ti koong": "天仁茗茶 天宮茶",
    "ten ren ti kuan": "天仁茗茶 天寬茶",
    "ten ren tung ting": "天仁茗茶 凍頂烏龍茶",
    "ten ren whole leaves": "天仁茗茶 散葉茶",
    "tsit wing coffe": "捷榮咖啡",
    "tsit wing tea bag": "捷榮茶包系列",
    "tsit wing milk tea":"捷榮奶茶系列",
    "tsit wing yuan yang": "捷榮鴛鴦",
    "twinings tea bag": "川寧茶包系列",
    "ucc coffee": "Ucc咖啡系列",
    "ueshima coffee": "上島咖啡咖啡系列",
    "ujinotsuyu jpn tea t-bag": "宇治之茶包",
    "van houten cocoa powder": "金鷹可可粉",
    "viaggio caps": "Viaggio咖啡膠囊",
    "waitrose tea bag": "Waitrose茶包系列",
    "waitrose coffee": "Waitrose咖啡系列",
    "way choy tea": "日月牌茶飲系列",
    "yu pin king tea": "御品皇茶包系列",
    "imperial choic tea": "御茗茶飲系列",
    "bovril yeast extract": "保衛爾酵母素"

   
],
  "果汁": [
      "beckers bester cloudy apple juice": "Beckers Bester德國雲蘋果汁",
      "bickford's natural lime juice cordial": "Bickford's天然青檸濃縮飲品",
      "black & gold drink": "Black & Gold果汁飲品系列",
      "casino bio organic multifruits pure juice": "Casino Bio有機雜果純果汁",
      "casino juice": "Casino果汁系列",
      "cawston apple rhubarb juice drink": "Cawston蘋果大黃汁飲品",
      "ceres juice": "Ceres 100果汁系列",
      "chung jung one red vinegar": "清淨園紅醋飲品系列",
      "cocomax coconut water": "Cocomax椰子水",
      "cocoway coconut water": "Cocoway椰子水",
      "community co. coconut water": "Community Co.椰子水",
      "cou-su vinegar": "一斤果醋系列",
      "coudo concentrated mango juice": "Coudo濃縮芒果汁",
      "del monte juice": "地捫果汁系列",
      "dole water jelly mango": "Dole芒果啫喱水飲品",
      "don simon apple juice": "Don Simon蘋果汁",
      "don simon orange juice with pulp": "Don Simon有果肉橙汁",
      "don simon peach & grape juice": "Don Simon桃子提子混合汁",
      "don simon red grape juice": "Don Simon紅提子汁",
      "essential waitrose pure apple juice": "Essential Waitrose純蘋果汁",
      "food nation natural coconut water": "Food Nation天然椰子水",
      "four seas tsubu tsubu orange drink": "四洲粒粒橙味飲品",
      "fresh berries juice": "鮮莓果汁",
      "golden circle apple juice": "Golden Circle蘋果汁",
      "golden circle orange juice": "Golden Circle橙汁",
      "gua juice": "GUA果汁飲品系列",
      "hi-c apple juice": "陽光蘋果飲品汁",
      "hi-c lemon blackcurrant": "陽光檸檬黑加侖子飲品",
      "hi-c orange juice": "陽光橙汁飲品",
      "hi-c pineapple": "陽光菠蘿汁飲品",
      "homegrown cold pressed juice": "Homegrown冷壓果汁系列",
      "homegrown probio kiwi juice": "Homegrown益生菌奇異果汁",
      "homegrown raw energy cold pressed juice": "Homegrown活力冷壓果汁",
      "if 100% coconut water": "iF 100%椰子水",
      "if 100% coconut water with coconut pulp": "iF 100%椰子水（椰果肉）",
      "if 100% natural coconut water": "iF 100%天然椰子水",
      "if peach juice drink": "iF桃味果汁飲品",
      "itamachi coconut milk drink": "Itamachi椰奶飲品",
      "ja aoren premium apple juice": "JA Aoren優質蘋果汁",
      "james white organic carrot & apple juice": "James White有機紅蘿蔔蘋果汁",
      "jax coco coconut water": "Jax Coco椰子水",
      "kagome apple mixed juice": "Kagome蘋果混合果汁",
      "kagome carrot mixed juice": "Kagome紅蘿蔔混合果汁",
      "kagome grape mixed juice": "Kagome提子混合果汁",
      "kagome mango mixed juice": "Kagome芒果混合果汁",
      "kagome mixed carrot juice": "Kagome混合紅蘿蔔果汁",
      "kagome mixed mango juice": "Kagome混合芒果果汁",
      "kagome tomato juice": "Kagome蕃茄汁",
      "kagome vegetable juice": "Kagome蔬菜汁",
      "koh coconut water": "KOH椰子水",
      "malee coconut water": "Malee椰子水",
      "meadows coconut water": "Meadows椰子水",
      "meko coconut water": "Meko椰子水",
      "meko coconut water case": "Meko椰子水箱裝",
      "meko pure coconut water": "Meko純椰子水",
      "meysu juice": "Meysu果汁系列",
      "minute maid orange juice drink": "Minute Maid橙味果汁飲品",
      "minute maid qoo apple juice drink": "Qoo蘋果汁飲品",
      "minute maid qoo blackcurrant juice drink": "Qoo黑加侖子汁飲品",
      "minute maid qoo peach juice drink": "Qoo桃汁飲品",
      "minute maid qoo white grape juice drink": "Qoo白提子汁飲品",
      "minute maid white grape juice drink": "美粒果白提子汁飲品",
      "mr. juicy apple juice": "維他果汁先生蘋果汁",
      "mr. juicy coconut water": "維他果汁先生椰子水",
      "mr. juicy orange juice": "維他果汁先生橙汁",
      "mysmoothie smoothie": "Mysmoothie果昔系列",
      "nature's sen organic pomegranate juice": "Nature's Sen有機果汁系列",
      "nissin green juice": "日清青汁系列",
      "ocean spray cranberry juice": "Ocean Spray果汁飲品系列",
      "okf farms yogurt": "OKF乳酪飲品系列",
      "paldo pororo drink": "Pororo飲品系列",
      "popper juice apple juice": "Popper蘋果汁",
      "rabenhorst juice": "Rabenhorst果汁系列",
      "ready orange juice with pulp": "Ready有果肉橙汁",
      "ready pineapple juice": "Ready菠蘿汁",
      "ribena blackcurrant drink": "Ribena黑加侖子飲品",
      "ribena concentrate": "Ribena濃縮黑加侖子",
      "simply kids juice": "Simply Kids果汁系列",
      "sunkist sparkling grapefruit juice drink": "Sunkist有氣西柚汁飲品",
      "sunquick orange cordial": "Sunquick橙味濃縮果汁",
      "sunraysia cranberry juice": "Sunraysia蔓越莓汁",
      "sunraysia prune juice": "Sunraysia西梅汁",
      "sunsweet prune juice": "Sunsweet西梅汁",
      "tao ti grape kyoho juice": "道地巨峰提子汁",
      "tao ti lychee juice drink": "道地荔枝果汁飲品",
      "tao ti mandarin lemon juice drink": "道地柑橘檸檬果汁飲品",
      "tao ti pak gor yuen mandarin lemon juice drink": "道地白果園柑檸果汁飲品",
      "the berry company juice": "The Berry Company果汁系列",
      "tian di no 1 apple vinegar drink": "天地一號蘋果醋飲品",
      "tree top apple juice": "Tree Top蘋果汁",
      "tree top orange juice": "Tree Top橙汁",
      "ufc coconut water": "UFC椰子水",
      "v8 vegetable juice": "V8蔬菜汁",
      "van nahmen apricot nectar": "Van Nahmen杏桃果汁",
      "vita apple juice": "維他蘋果汁",
      "vita blackcurrant juice": "維他黑加侖汁",
      "vita coco coconut water": "Vita Coco椰子水",
      "vita guava juice": "維他番石榴汁",
      "vita guava juice drink": "維他番石榴汁",
      "vita juice guava drink": "維他果汁番石榴飲品",
      "vita mango juice drink": "維他芒果果汁",
      "welch's grape juice": "Welch's提子汁",
      "welch's pure grape juice": "Welch's純提子汁",
      "welch's zero sugar grape juice": "Welch's零糖提子汁",
      "yeshu coconut juice beverage": "椰樹椰汁飲品",
      "it's manuka drink":"天然麥盧卡蜜糖飲品系列"
      ],
  "運動及能量飲品": [

    "100plus active electro drink": "100PLUS 電解質運動飲品",
     "alienergy electrolyte drink": "外星人電解質飲品",
     "aquarius electrolyte replenishment drink": "水動樂電解質補充飲品",
     "aquarius electrolyte replenishment drink case": "水動樂電解質補充飲品(箱裝）",
     "aquarius electrolytes replenish drink zero": "水動樂無糖電解質補充飲品",
     "aquarius electrolytes replenishment drink powder": "水動樂電解質補充飲品粉裝",
     "barebells milk shake": "Barebells乳清蛋白奶昔",
     "celsius fitness drink sparkling white peach": "Celsius健身氣泡飲白桃味",
     "drinkazine energy drink case 20 x 800 ml": "解渴誌沛力特箱裝）",
     "eastroc vitamin energy drink": "東鵬維生素特飲",
     "gatorade drinks": "Gatorade佳得樂運動飲品",
     "gnc protein drinks": "GNC蛋白質飲品",
     "labrada protein drinks": "Labrada蛋白質飲品",
     "lean body protein shake": "Lean Body高蛋白奶昔",
     "libogen tonic drink": "Libogen精力補身飲品",
     "lucozade energy drink low sugar orange": "葡萄適低糖橙味能量飲品",
     "lucozade energy drink orange flavour": "葡萄適橙味能量飲品",
     "lucozade energy drink original": "葡萄適原味能量飲品",
  "lucozade sport orange": "葡萄適Sport橙味運動飲品",
  "monster energy drink": "Monster能量飲品",
  "monster energy drink ultra": "Monster Ultra系列能量飲品",
  "monster mango loco": "Monster 芒果能量飲品",
  "monster peachy keen": "Monster 蜜桃能量飲品",
  "oronamin c oronamin c": "Oronamin C維他命飲品",
  "pocari ion supply drink": "寶礦力水特電解質飲品",
  "pocari sweat ion supply drink case": "寶礦力水特電解質飲品（箱裝）",
  "pocari ion water low kcal": "寶礦力水特低卡電解質水",
  "prime drinks": "Prime電解質飲品",
    "red bull apple muscat sparkling energy drink": "Red Bull青蘋果麝香葡萄味能量飲品",
    "red bull energy drink": "Red Bull能量飲品",
    "red bull kyoho grape": "Red Bull巨峰提子味能量飲品",
    "red bull pomelo sparkling energy drink": "Red Bull柚子味氣泡能量飲品",
    "red bull drink": "Red Bull能量飲品系列",
    "sis hydro": "SIS電解補水水溶片系列",
    "sis hydro tablet lemon": "SIS 水解檸檬味片",
    "v energy original": "V能量飲品",
    "weider in jelly energy in": "WEIDER IN JELLY能量果凍",
    "you c1000 vitamin": "You-C1000維他命飲品系列",
  ],
  "涼茶": [
    "healthworks hawthorn apple":"健康工房山楂蘋果飲品",
    "healthworks lemon yiyiren":"健康工房檸檬薏米飲品",
    "healthworks rock sugar with pear":"健康工房冰糖雪梨飲品",
    "healthworks self heal spike":"健康工房夏枯草飲品",
    "healthworks sugarcane rhizoma imperatae and sea coconut":"健康工房竹蔗茅根海底椰飲品",
    "healthworks sugarcane sea coconut":"健康工房竹蔗海底椰飲品",
    "healthworks sugarcane seacoconut":"健康工房竹蔗茅根海底椰飲品",
    "hoi tin tong drinks":"海天堂涼茶系列",
    "hung fook tong american ginsing with honey":"鴻福堂花旗參蜜飲品",
    "hung fook tong brewing american ginseng":"鴻福堂花旗參系列飲品",
    "hung fook tong chrysanthemum with honey":"鴻褔堂銀菊露飲品",
    "hung fook tong fig w apple water chestnut":"鴻福堂馬蹄無花果茶",
    "hung fook tong floral herbal":"鴻福堂五花茶飲品",
    "hung fook tong ginseng with honey":"鴻福堂人參蜜飲",
    "hung fook tong honey drk w fritillary loquat leaves":"鴻福堂川貝枇杷潤肺茶",
    "hung fook tong honey drk w mulberry mulberry leaf":"鴻福堂桑椹桑葉茶",
    "hung fook tong honey w chuan bei loquat leave":"鴻福堂川貝枇杷蜜飲品",
    "hung fook tong hung fook tong pear and chrysanthemum":"鴻福堂雪梨菊花茶飲品",
    "hung fook tong imperatae cane":"鴻福堂竹蔗茅根飲品",
    "hung fook tong pear":"鴻福堂雪梨茶",
    "hung fook tong salted lime":"鴻福堂咸青檸飲品",
    "hung fook tong salted mandarin":"鴻福堂咸柑桔飲品",
    "hung fook tong sour plum":"鴻福堂酸梅湯飲品",
    "hung fook tong sugarcane juice":"鴻福堂竹蔗汁",
    "hung fook tong tangerine peel mandarin":"鴻福堂陳皮柑桔飲品",
    "jia duo bao herbal":"加多寶涼茶系列",
    "kirin rich green series origin flavor":"nonshow",
    "tao ti supreme meta":"nonshow",
    "tao ti supreme meta slim":"nonshow",
    "vedan winter melon":"味丹心茶道冬瓜茶",
    "vita apple jasmine juice":"維他清心棧冬蘋果茉莉飲品",
    "vita sugar cane imperatae":"維他清心棧冬竹蔗茅根飲品",
    "vita tsing sum zhan honey lime healthy":"維他清心棧冬蜜青檸飲品",
    "vita tsz apple and jasmine":"維他蘋果茉莉飲品",
    "vita tsz sugar cane and imperatae":"維他竹蔗茅根飲品",
    "yeo s grass jelly":"楊協成清涼爽",
    "yeo s yeo s herb set":"楊協成涼茶套裝",
    "yeo s yeo s white gourd":"楊協成冬瓜茶",

    "hung fook tong canton love pea vine":"鴻褔堂雞骨草",
    "hung fook tong common selfheal fruit spike":"鴻褔堂夏枯草",
    "hung fook tong grosvenor momordica fruit":"鴻褔堂無糖羅漢果",
    "hung fook tong sugarcane and sea coconut with carrot":"鴻褔堂竹蔗甘筍海底椰飲品",
    "meadows grosvenor momordica":"Meadows羅漢果飲品",
    "meadows imperatae cane":"Meadows竹蔗茅根飲品",
    "mj x hft lemon coix seeds":"菓汁先生X鴻福堂檸檬薏米飲品",
    "mj x hft mj x hft red bean coix seeds":"菓汁先生X鴻福堂紅豆薏米飲品",
    "mr juicy honey pear juice":"菓汁先生蜂蜜雪梨果汁飲品",
    "mr juicy sugarcane water chestnut juice":"菓汁先生竹蔗馬蹄果汁飲品",
    "mzk life honey sugar fig":"花研草說冰糖蜂蜜皇菊茶",
    "mzk life osmanthus snow pear":"花研草說桂花雪梨潤肺茶",
    "original taste carrot pear":"原味家作甘筍雪梨茶",
    "original taste chrysanthemum w honey":"原味家作原味家作菊花蜜露",
    "original taste fig apple pear":"原味家作無花果蘋果雪梨茶",
    "original taste fresh citrus with coix seed":"原味家作鮮柑桔薏米露",
    "original taste fresh lemon with coix seed":"原味家作鮮檸檬薏米露",
    "original taste fresh peach with coix seed":"原味家作鮮蜜桃薏米露",
    "original taste pear sichuan loquat":"原味家作雪梨川貝枇杷蜜",
    "sensa cools herbal chrysanthemum": "清熱酷百花菊茶",
    "sensa cools herbal green": "清熱酷草本綠茶",
    "sensa cools herbal lemon": "清熱酷草本檸檬茶"
    
  ],
  "啤酒": [
    "asahi": "朝日啤酒啤酒系列",
    "blue girl": "藍妹啤酒",
    "blue girl light": "藍妹清啤",
    "blue ice": "藍冰啤酒",
    "blue ice filtered": "藍冰啤酒",
    "boddingtons pub ale": "Boddingtons啤酒",
    "brewdog": "Brewdog啤酒系列",
    "bruck lager": "布萊特啤酒",
    "budweiser": "百威啤酒",
    "carbon brews feels good man wheat": "Carbon Brews Feels Good Man啤酒",
    "carlsberg": "嘉士伯啤酒",
    "carlsberg danish brew":"嘉士伯巨罐金牌啤酒",
    "chang": "泰象啤酒",
    "corona extra": "Corona啤酒",
    "erdinger": "艾丁格啤酒系列",
    "gs retail youus": "Gs Retail Youus手工啤酒系列",
    "guinness": "健力士黑啤酒",
    "gweilo beer pale ale": "鬼佬啤酒",
    "harbin": "哈爾濱啤酒",
    "heineken": "喜力啤酒",
    "heineken silver": "喜力星銀啤酒",
    "hite 1933": "海特啤酒系列",
    "hoegaarden": "好卡頓啤酒系列",
    "jolly shandy lemon": "樂怡仙地",
    "kingway": "金威啤酒",
    "kirin ichiban": "麒麟一番搾啤酒",
    "kirin ichiban japan prime brew": "麒麟一番搾啤酒",
    "knight": "Knight啤酒",
    "kronenbourg 1664": "1664啤酒系列",
    "leffe blond": "Leffe啤酒",
    "little creatures": "Little Creatures啤酒系列",
    "murphy s stout": "麥菲士愛爾蘭黑啤",
    "orion draft": "Orion啤酒",
    "paulaner": "保拉納小麥啤酒系列",
    "peroni": "Peroni啤酒",
    "san miguel": "生力啤酒",
    "san miguel blanca": "生力白啤",
    "san miguel light": "生力清啤",
    "san miguel pale pilsen": "查無資料21",
    "san miguel philippines": "生力菲律賓樽裝啤酒",
    "sapporo": "三寶樂啤酒",
    "sapporo hokkaido": "札幌啤酒系列",
    "singha": "勁獅啤酒",
    "skol": "獅威啤酒",
    "skol refreshing": "獅威啤酒",
    "snow": "雪花勇闖天涯啤酒",
    "sonderberg": "森堡啤酒",
    "stella artois": "Stella Artois啤酒系列",
    "suntory premium malt": "三得利頂級啤酒",
    "gold medal taiwan beer": "金牌台灣啤酒",
    "taiwan beer fruit flv":"台灣啤酒水果系列",
    "taiwan beer sweet touch fruit beer":"台灣啤酒果微醺系列",
    "takaha chu hi shine muscat": "宝洒造啤酒",
    "tsing tao beer": "青島啤酒",
    "tsing tao king beer":"青島巨罐裝啤酒",
    "carlsberg smooth draft":"嘉士伯醇滑啤酒",
    "tsing tao draft": "青島純生啤酒",
    "tsing tao lager": "查無資料34",
    "tsing tao lemon pilsner non alcoholic": "青島零度檸檬啤酒",
    "tsing tao light": "青島清啤",
    "tsing tao pure draft": "查無資料37",
    "tsing tao snake": "青島蛇年啤酒(限量版)",
    "tsing tao stout": "青島黑啤",
    "tsing tao wheat": "青島白啤",
    "tsing tao zero": "青島零度啤酒",
    "wusu": "烏蘇啤酒",
    "young masterclass": "少爺啤酒系列",
    "yebisu": "惠比壽啤酒",
    "yanjing draft":"燕京啤酒"
    
  ],
  "紅酒":
    [
      // 19 Crimes
      "19 crimes blend red":                           "19 Crimes 紅混合酒",
      "19 crimes cabernet sauvignon":                  "19 Crimes 赤霞珠",
      "19 crimes shiraz":                              "19 Crimes 西拉",

      // Abtei Himmerod
      "abtei himmerod riesling spatlese":              "Abtei Himmerod 雷司令晚收甜白酒",

      // Allees Cante
      "allees cante haut medoc":                       "Allees de Cantemerle (康特梅爾副牌)",

      // Anakena
      "anakena nuna carmenere":                        "Anakena Nuna 佳美娜",
      "anakena nuna malbec":                           "Anakena Nuna 馬爾貝克",

      // Aney
      "aney haut medoc":                               "Chateau Aney Haut Medoc",

      // Antu
      "antu cabernet sauvignon":                       "Antu 赤霞珠",
      "antu shiraz":                                   "Antu 西拉",

      // Apothic (耶波席)
      "apothic blend red":                             "Apothic 紅混合酒",
      "apothic cabernet sauvignon":                    "Apothic 赤霞珠",
      "apothic crush":                                 "Apothic Crush",
      "apothic dark":                                  "Apothic Dark",

      // Arrogant Frog (傲蛙)
      "arrogant frog cabernet sauvignon merlot cuvee": "Arrogant Frog 赤霞珠梅洛",
      "arrogant frog tutti frutti":                    "Arrogant Frog Tutti Frutti",

      // Avamposti
      "avamposti piemonte pinot noir":                 "Avamposti 皮埃蒙特黑皮諾",

      // Babich
      "babich winemakers pinot noir reserve":          "Babich Winemakers 黑皮諾珍藏",

      // Banrock Station (班洛克)
      "banrock station shiraz":                        "Banrock Station 西拉",
      "banrock station shiraz cabernet":               "Banrock Station 西拉赤霞珠",

      // Barefoot
      "barefoot cabernet sauvignon":                   "Barefoot 赤霞珠",
      "barefoot merlot":                               "Barefoot 梅洛",
      "barefoot rich blend red":                       "Barefoot 濃郁紅混合酒",

      // Baron
      "baron philippe rothschild bordeaux":            "Baron Philippe de Rothschild 波爾多紅酒",
      "baron richemont bordeaux superieur":            "Baron Richemont 優質波爾多",

      // Beefsteak Club
      "beefsteak club malbec":                         "Beefsteak Club 馬爾貝克",
      "beefsteak club shiraz":                         "Beefsteak Club 西拉",

      // Beringer (貝靈哲)
      "beringer founders estate pinot noir":           "Beringer Founders' Estate 黑皮諾",

      // Bodega Norton (諾頓)
      "bodega norton 1895 coleccion malbec":           "Bodega Norton 1895 馬爾貝克",

      // Bodegas Riojanas
      "bodegas riojanas monte real blanco":            "Monte Real 白酒",
      "bodegas riojanas monte real crianza":           "Monte Real 陳釀紅酒",

      // Bonpas
      "bonpas cotes red rhone":                        "Bonpas 隆河谷紅酒",
      "bonpas cotes rhone villages plan dieu":         "Bonpas 隆河谷村莊級紅酒",

      // De Bortoli
      "bortoli noble one":                             "De Bortoli Noble One 貴腐甜酒",

      // Calvet (卡爾維特)
      "calvet reserve bordeaux":                       "Calvet 珍藏波爾多紅酒",

      // Campo Viejo (帝田)
      "campo viejo rioja reserva":                     "Campo Viejo 里奧哈珍藏紅酒",

      // Cape Kaki
      "cape kaki marlborough pinot noir":              "Cape Kaki 馬爾堡黑皮諾",

      // Carlo Rossi (加州樂事)
      "carlo rossi california dark red":               "加州樂事 黑紅酒 (Dark Red)",
      "carlo rossi california red":                    "加州樂事 紅酒 (Red)",
      "carlo rossi moscato red":                       "加州樂事 莫斯卡托甜紅酒",

      // Carnivor
      "carnivor bourbon barrel aged cabernet sauvignon": "Carnivor 波本桶陳釀赤霞珠",
      "carnivor zinfandel":                            "Carnivor 仙粉黛",

      // Cartillon
      "cartillon haut medoc":                          "Chateau Cartillon Haut Medoc",

      // Castelmaure
      "castelmaure corbieres":                         "Castelmaure Corbieres",

      // Castillo Albai
      "castillo albai rioja joven":                    "Castillo Albai 里奧哈新酒",
      "castillo albai rioja reserva":                  "Castillo Albai 里奧哈珍藏",

      // Cel Des Dauphins
      "cel des dauphins red":                          "Cel Des Dauphins 紅酒",
      "cel des dauphins white":                        "Cel Des Dauphins 白酒",

      // Cellar Selection
      "cellar selection ac bordeaux red":              "Cellar Selection 波爾多紅酒",
      "cellar selection bergerac red":                 "Cellar Selection 貝傑拉克紅酒",

      // Chateau (酒莊)
      "ch belles eaux les coteaux":                    "Chateau Belles Eaux Les Coteaux",
      "ch brandey aoc bordeaux":                       "Chateau Brandey 波爾多",
      "ch ferrande graves":                            "Chateau Ferrande 格拉夫",
      "ch fonpiqueyre haut medoc":                     "Chateau Fonpiqueyre 上梅多克",
      "ch garat bel air bordeaux":                     "Chateau Garat Bel Air 波爾多",
      "ch latour camblanes aoc 1res cotes bordeaux":   "Chateau Latour Camblanes 波爾多首丘",
      "ch laville bertrou minervois":                  "Chateau Laville Bertrou",
      "ch lieujean haut medoc cru bourgeois":          "Chateau Lieujean 上梅多克中級莊",
      "ch liversan haut medoc cru bourgeois":          "Chateau Liversan 上梅多克中級莊",
      "ch lynch bages":                                "Chateau Lynch Bages (靚次伯)",
      "ch meaume bordeaux superieur":                  "Chateau Meaume 優質波爾多",
      "ch montrose tertio montrose":                   "Le Tertio de Montrose (玫瑰山莊三牌)",
      "ch rougi bordeaux":                             "Chateau Rougi 波爾多",
      "ch ste michelle cabernet sauvignon":            "Chateau Ste Michelle 赤霞珠",
      "ch tour prignac aoc medoc":                     "Chateau Tour Prignac 梅多克",
      
      // Famous Chateaus
      "chateau bourdieu blaye cotes bordeaux":         "Chateau Bourdieu 布萊伊",
      "chateau brane cantenac margaux":                "Chateau Brane-Cantenac (布朗康田)",
      "chateau brown pessac leognan":                  "Chateau Brown 佩薩克-雷奧良",
      "chateau camensac haut medoc":                   "Chateau Camensac (卡門薩克)",
      "chateau carbonnieux pessac leognan":            "Chateau Carbonnieux (卡爾邦女)",
      "chateau citran haut medoc":                     "Chateau Citran (西特蘭)",
      "chateau clinet petit ronan bordeaux":           "Ronan by Clinet 波爾多",
      "chateau conseillante duo pomerol":              "Duo de Conseillante (康賽揚副牌)",
      "chateau daiguilhe castillon bordeaux":          "Chateau d'Aiguilhe (艾吉爾)",
      "chateau ducru beaucaillou haut medoc":          "Chateau Ducru-Beaucaillou (寶嘉龍)",
      "chateau faugeres saint emilion":                "Chateau Faugeres (福熱爾)",
      "chateau fieuzal pessac leognan":                "Chateau de Fieuzal (菲熱爾)",
      "chateau fleur bouard lalande pomerol":          "Chateau La Fleur de Bouard",
      "chateau gemeillan medoc":                       "Chateau Gemeillan 梅多克",
      "chateau giscours":                              "Chateau Giscours (美人魚)",
      "chateau haut bergey pessac leognan":            "Chateau Haut-Bergey",
      "chateau holden haut medoc":                     "Chateau Holden 上梅多克",
      "chateau lanessan haut medoc":                   "Chateau Lanessan 上梅多克",
      "chateau langoa barton saint julien":            "Chateau Langoa Barton (朗高巴頓)",
      "chateau larrivet haut brion pessac leognan":    "Chateau Larrivet Haut-Brion",
      "chateau les bertrands blaye bordeaux":          "Chateau Les Bertrands",
      "chateau les vallees bordeaux":                  "Chateau Les Vallees",
      "chateau lilian ladouys saint estephe":          "Chateau Lilian Ladouys (麗蓮)",
      "chateau mareil medoc":                          "Chateau Mareil 梅多克",
      "chateau pape clement pessac leognan":           "Chateau Pape Clement (黑教皇)",
      "chateau puygueraud francs bordeaux":            "Chateau Puygueraud",
      "chateau romefort haut medoc":                   "Chateau Romefort 上梅多克",
      "chateau simard saint emilion":                  "Chateau Simard 聖埃美隆",
      "chateau talbot connetable saint julien":        "Connetable Talbot (大寶副牌)",
      "chateau tour carnet haut medoc":                "Chateau La Tour Carnet",
      
      // Others
      "chap moines saint emilion":                     "Chapelle des Moines 聖埃美隆",
      "chapel hill parson gsm":                        "Chapel Hill The Parson GSM",
      "chemin des papes cotes rhone white":            "Chemin des Papes 隆河谷白酒",
      "circumference napa cabernet sauvignon":         "Circumference 納帕谷赤霞珠",
      
      // Clarendelle
      "clarendelle medoc":                             "Clarendelle 梅多克",
      "clarendelle rouge":                             "Clarendelle 波爾多紅酒",
      "clarendelle saint emilion":                     "Clarendelle 聖埃美隆",
      
      "clos dominique bordeaux superieur":             "Clos Dominique 優質波爾多",
      "con de oriza ribera del duero":                 "Con de Oriza",
      
      // Concha y Toro (干露)
      "concha y toro casillero del diablo cabernet sauvignon": "紅魔鬼 (Casillero del Diablo) 赤霞珠",
      "concha y toro casillero del diablo merlot":     "紅魔鬼 (Casillero del Diablo) 梅洛",
      "concha y toro marques de casa cabernet sauvignon": "Concha y Toro 麥卡斯赤霞珠",
      
      "confidences de prieure lichine margaux":        "Confidences de Prieure-Lichine (荔仙副牌)",
      
      // Cono Sur (單車)
      "cono sur bicicleta cabernet":                   "Cono Sur Bicicleta 赤霞珠",
      "cono sur bicicleta pinot noir":                 "Cono Sur Bicicleta 黑皮諾",
      "cono sur single vineyard cabernet sauvignon":   "Cono Sur 單一葡萄園赤霞珠",
      "cono sur single vineyard pinot noir":           "Cono Sur 單一葡萄園黑皮諾",
      
      "cote mas syrah grenache":                       "Cote Mas 西拉歌海娜",
      "croix montlabert saint emilion":                "Croix de Montlabert 聖埃美隆",
      "darcins haut medoc":                            "Chateau d'Arcins 上梅多克",
      "dark horse california cabernet sauvignon":      "Dark Horse 加州赤霞珠",
      
      // DBR Lafite (拉菲羅斯柴爾德)
      "dbr lafite aussieres rouge":                    "拉菲奧希耶 (Aussieres Rouge)",
      "dbr lafite chateau paradis casseuil":           "拉菲凱薩天堂古堡",
      "dom daussieres altan":                          "Altan d'Aussieres",
      "lafite aussieres classique cabernet syrah":     "拉菲奧希耶經典",
      "lafite terrasses d'aussieres corbieres":        "拉菲奧希耶泰瑞",
      "legende medoc":                                 "Legende (拉菲傳奇) 梅多克",
      "saga bordeaux":                                 "Saga (拉菲傳說) 波爾多",
      
      "don luciano tempranillo":                       "Don Luciano 丹魄",
      
      // E. Guigal
      "e guigal cotes du rhone rouge":                 "E. Guigal 隆河谷紅酒",
      "e guigal gigondas":                             "E. Guigal 吉貢達斯",
      
      "edmond de rothschild croix des laurets":        "Edmond de Rothschild 勞瑞得",
      "emalee estate barossa shiraz":                  "Emalee Estate 巴羅薩西拉",
      "emalee estate cabernet sauvignon":              "Emalee Estate 赤霞珠",
      "emalee estate shiraz":                          "Emalee Estate 西拉",
      "fam lapalu medoc":                              "Famille Lapalu 梅多克",
      "frank family napa cabernet sauvignon":          "Frank Family 納帕谷赤霞珠",
      "frank family napa zinfandel":                   "Frank Family 納帕谷仙粉黛",
      "franzia red":                                   "Franzia 紅酒",
      
      // French Cellars
      "french cellars cabernet sauvignon":             "French Cellars 赤霞珠",
      "french cellars grenache shiraz":                "French Cellars 歌海娜西拉",
      "french cellars merlot":                         "French Cellars 梅洛",
      "french cellars pinot noir":                     "French Cellars 黑皮諾",
      "french cellars shiraz":                         "French Cellars 西拉",
      
      "frescobaldi tenuta di castiglioni":             "Frescobaldi (花思蝶) Castiglioni",
      "genestras medoc":                               "Chateau Genestras 梅多克",
      
      // George Wyndham (喬治雲咸)
      "george wyndham bin 444 cabernet sauvignon":     "George Wyndham Bin 444 赤霞珠",
      "george wyndham bin 555 shiraz":                 "George Wyndham Bin 555 西拉",
      "george wyndham bin 888 cabernet merlot":        "George Wyndham Bin 888 赤霞珠梅洛",
      
      "gerard bertrand cotes du roussillon":           "Gerard Bertrand 魯西榮",
      "gerard bertrand saint chinian":                 "Gerard Bertrand 聖席尼昂",
      "grand bateau bordeaux rouge":                   "Grand Bateau (小龍船) 波爾多紅酒",
      "grand meynau bordeaux":                         "Grand Meynau 波爾多",
      
      // Grant Burge
      "grant burge abednego barossa gsm":              "Grant Burge Abednego GSM",
      "grant burge balthasar shiraz":                  "Grant Burge Balthasar 西拉",
      "grant burge barossa cabernet merlot 5th generation": "Grant Burge 第五代 赤霞珠梅洛",
      "grant burge barossa ink cabernet sauvignon":    "Grant Burge Barossa Ink 赤霞珠",
      "grant burge barossa ink shiraz":                "Grant Burge Barossa Ink 西拉",
      "grant burge barossa shiraz 5th generation":     "Grant Burge 第五代 西拉",
      "grant burge corryton park cabernet sauvignon":  "Grant Burge Corryton Park 赤霞珠",
      "grant burge 5th generation cabernet merlot":    "Grant Burge 第五代 赤霞珠梅洛",
      "grant burge 5th generation shiraz":             "Grant Burge 第五代 西拉",
      "grant burge filsell old vine shiraz":           "Grant Burge Filsell 老藤西拉",
      "grant burge gb51 cabernet shiraz":              "Grant Burge GB51 赤霞珠西拉",
      "grant burge gb56 series shiraz":                "Grant Burge GB56 西拉",
      "grant burge gb88 series cabernet sauvignon":    "Grant Burge GB88 赤霞珠",
      "grant burge holy trinity gsm":                  "Grant Burge Holy Trinity GSM",
      "grant burge ink coonawarra cabernet sauvignon": "Grant Burge Ink 庫納瓦拉赤霞珠",
      "grant burge ink mclaren vale shiraz":           "Grant Burge Ink 麥拿倫谷西拉",
      "grant burge miamba shiraz":                     "Grant Burge Miamba 西拉",
      "grant burge nebu cabernet shiraz":              "Grant Burge Nebu 赤霞珠西拉",
      "grant burge shadrach barossa cabernet sauvignon": "Grant Burge Shadrach 赤霞珠",
      
      "h faugeres saint emilion grand cru":            "Cap de Faugeres 聖埃美隆",
      
      // Hahn
      "hahn cabernet sauvignon":                       "Hahn 赤霞珠",
      "hahn gsm":                                      "Hahn GSM",
      "hahn pinot noir":                               "Hahn 黑皮諾",
      "hahn slh pinot noir":                           "Hahn SLH 黑皮諾",
      
      // St Hallett
      "st hallett blackclay shiraz":                   "St Hallett Blackclay 西拉",
      "st hallett blackwell shiraz":                   "St Hallett Blackwell 西拉",
      "st hallett butchers cart shiraz":               "St Hallett Butchers Cart 西拉",
      "st hallett faith shiraz":                       "St Hallett Faith 西拉",
      "st hallett old block shiraz":                   "St Hallett Old Block 西拉",
      
      // Hardys (夏迪)
      "hardys cabernet sauvignon":                     "Hardys 赤霞珠",
      "hardys eileen hardys shiraz":                   "Hardys Eileen Hardy 西拉",
      "hardys hrb cabernet sauvignon":                 "Hardys HRB 赤霞珠",
      "hardys hrb pinot noir":                         "Hardys HRB 黑皮諾",
      "hardys hrb shiraz":                             "Hardys HRB 西拉",
      "hardys nottage hill cabernet shiraz":           "Hardys Nottage Hill 赤霞珠西拉",
      "hardys nottage hill shiraz":                    "Hardys Nottage Hill 西拉",
      "hardys shiraz cask":                            "Hardys 西拉 (盒裝)",
      "hardys stamp shiraz cabernet":                  "Hardys Stamp 西拉赤霞珠",
      "hardys thomas hardy cabernet sauvignon":        "Hardys Thomas Hardy 赤霞珠",
      "hardys tintara reserve grenache":               "Hardys Tintara 歌海娜",
      "hardys vr cabernet sauvignon":                  "Hardys VR 赤霞珠",
      "hardys vr merlot":                              "Hardys VR 梅洛",
      "hardys vr shiraz":                              "Hardys VR 西拉",
      "hardys zero alcohol shiraz":                    "Hardys 無酒精西拉",
      
      "le haut medoc dissan":                          "Le Haut-Medoc d'Issan (迪仙副牌)",
      "ht branaire ducru haut medoc":                  "Chateau Branaire-Ducru (周伯通)",
      "st hugo cabernet sauvignon":                    "St Hugo 赤霞珠",
      
      // Jacob's Creek (傑卡斯)
      "jacobs creek cabernet":                         "Jacob's Creek 赤霞珠",
      "jacobs creek classic shiraz cabernet":          "Jacob's Creek 經典西拉赤霞珠",
      "jacobs creek double barrel red":                "Jacob's Creek 雙桶紅酒",
      "jacobs creek double barrel cabernet":           "Jacob's Creek 雙桶赤霞珠",
      "jacobs creek double barrel shiraz":             "Jacob's Creek 雙桶西拉",
      "jacobs creek reserve cabernet sauvignon":       "Jacob's Creek 珍藏赤霞珠",
      "jacobs creek reserve shiraz":                   "Jacob's Creek 珍藏西拉",
      "jacobs creek shiraz cabernet":                  "Jacob's Creek 西拉赤霞珠",
      
      "jalousie beaulieu chateau jalousie beaulieu":   "Chateau Jalousie Beaulieu",
      "jean bouchard cote de beaune villages":         "Jean Bouchard 伯恩丘村莊級",
      "jean bouchard savigny les beaune premier cru":  "Jean Bouchard 薩維尼一級園",
      
      // JJ McWilliam
      "jj mcwilliam cabernet merlot":                  "JJ McWilliam 赤霞珠梅洛",
      "jj mcwilliam shiraz":                           "JJ McWilliam 西拉",
      "jj mcwilliam shiraz cabernet":                  "JJ McWilliam 西拉赤霞珠",
      
      "jp chenet cabernet syrah":                      "JP Chenet 赤霞珠西拉",
      "k constantia red blend":                        "Klein Constantia 紅混合酒",
      "k vintners milbrandt syrah":                    "K Vintners Milbrandt 西拉",
      "kaiken by montes malbec":                       "Kaiken (by Montes) 馬爾貝克",
      
      // Kangaroo Ridge (袋鼠山)
      "kangaroo ridge cabernet sauvignon":             "Kangaroo Ridge 赤霞珠",
      "kangaroo ridge merlot":                         "Kangaroo Ridge 梅洛",
      "kangaroo ridge shiraz":                         "Kangaroo Ridge 西拉",
      
      "kendall jackson reserve zinfandel":             "Kendall-Jackson 珍藏仙粉黛",
      "koyle reserve cabernet sauvignon":              "Koyle 珍藏赤霞珠",
      "koyle royale cabernet sauvignon":               "Koyle Royale 赤霞珠",
      "koyle royale carmenere":                        "Koyle Royale 佳美娜",
      "koyle royale syrah":                            "Koyle Royale 西拉",
      
      "les charmeuses bourgogne pinot noir":           "Les Charmeuses 勃艮第黑皮諾",
      "les fiefs de lagrange saint julien":            "Les Fiefs de Lagrange (拉格朗日副牌)",
      "les pelerins de lafon rochet saint estephe":    "Les Pelerins de Lafon-Rochet",
      "les pensees de la tour carnet haut medoc":      "Les Pensees de La Tour Carnet",
      "lescalle bordeaux superieur":                   "Lescalle 優質波爾多",
      "leydet valentin saint emilion":                 "Chateau Leydet-Valentin",
      
      // Lindemans (利達民)
      "lindemans cawarra cabernet merlot":             "Lindemans Cawarra 赤霞珠梅洛",
      "lindemans cawarra shiraz cabernet":             "Lindemans Cawarra 西拉赤霞珠",
      
      // Little Giant
      "little giant barossa shiraz":                   "Little Giant 巴羅薩西拉",
      "little giant coonawarra cabernet sauvignon":    "Little Giant 庫納瓦拉赤霞珠",
      "little giant pinot noir":                       "Little Giant 黑皮諾",
      
      "locations e spanish red":                       "Locations E 西班牙紅酒",
      
      // Los Vascos (巴斯克)
      "los vascos cabernet sauvignon":                 "Los Vascos 赤霞珠",
      "los vascos cromas cabernet sauvignon gran reserva": "Los Vascos Cromas 特級珍藏赤霞珠",
      "los vascos cromas carmenere gran reserva":      "Los Vascos Cromas 特級珍藏佳美娜",
      "los vascos cromas grande reserve":              "Los Vascos Cromas 特級珍藏紅酒",
      
      "louis latour cote de beaune villages":          "Louis Latour (路易拉圖) 伯恩丘村莊級",
      
      // M Cellars
      "m cellars cabernet sauvignon":                  "M Cellars 赤霞珠",
      "m cellars merlot":                              "M Cellars 梅洛",
      "m cellars pinot noir":                          "M Cellars 黑皮諾",
      "m cellars saint emilion":                       "M Cellars 聖埃美隆",
      "m cellars shiraz":                              "M Cellars 西拉",
      
      "mabalel pinot noir":                            "Mabalel 黑皮諾",
      "maison castel cabernet sauvignon":              "Maison Castel 赤霞珠",
      "sainte marguerite rose":                        "Sainte Marguerite 玫瑰紅酒",
      "marjosse bordeaux":                             "Marjosse 波爾多",
      
      // Marques de Riscal (瑞格爾侯爵)
      "marques de riscal proximo rioja":               "Marques de Riscal Proximo",
      "marques de riscal reserva rioja":               "Marques de Riscal 珍藏紅酒",
      "marques de riscal rueda blanco":                "Marques de Riscal 白酒",
      
      "matua marlborough pinot noir":                  "Matua 馬爾堡黑皮諾",
      "mcguigan black label cabernet merlot":          "McGuigan Black Label 赤霞珠梅洛",
      "michel lynch nature rouge":                     "Michel Lynch Nature 紅酒",
      "mission estate hawkes bay pinot gris":          "Mission Estate 灰皮諾",
      "mont olivet lirac":                             "Mont-Olivet Lirac",
      
      // MontGras
      "montgras day one cabernet sauvignon":           "MontGras Day One 赤霞珠",
      "montgras day one carmenere":                    "MontGras Day One 佳美娜",
      "montgras day one merlot":                       "MontGras Day One 梅洛",
      "montgras quatro reserva":                       "MontGras Quatro 珍藏",
      "montgras sauvignon blanc reserva":              "MontGras 珍藏長相思",
      
      // Montes
      "montes classic series malbec":                  "Montes 經典馬爾貝克",
      "montes classic series merlot":                  "Montes 經典梅洛",
      
      "motif cabernet sauvignon":                      "Motif 赤霞珠",
      "moulin dissan bordeaux superieur":              "Moulin d'Issan 優質波爾多",
      "mount peak gravity red blend":                  "Mount Peak Gravity 紅混合酒",
      "mount peak rattlesnake zinfandel":              "Mount Peak Rattlesnake 仙粉黛",
      
      // Mouton Cadet (武當嘉棣)
      "mouton cadet bordeaux":                         "Mouton Cadet (武當嘉棣) 波爾多",
      "mouton cadet reserve medoc":                    "Mouton Cadet (武當嘉棣) 珍藏梅多克",
      
      "mucho mas red blend":                           "Mucho Mas 紅混合酒",
      
      // Mud House
      "mud house central otago pinot noir":            "Mud House 中奧塔哥黑皮諾",
      
      "ox hardy mclaren vale grenache":                "Ox Hardy 歌海娜",
      
      // Oyster Bay (蠔灣)
      "oyster bay pinot gris":                         "Oyster Bay 灰皮諾",
      "oyster bay marlborough sauvignon blanc":        "Oyster Bay 馬爾堡長相思",
      "oyster bay merlot":                             "Oyster Bay 梅洛",
      
      "paloumey ailes de paloumey haut medoc":         "Ailes de Paloumey (帕露美副牌)",
      
      // Penfolds (奔富)
      "penfolds bin 128 coonawarra shiraz":            "Penfolds (奔富) Bin 128 庫納瓦拉西拉",
      "penfolds bin 138 barossa shiraz grenache mataro": "Penfolds (奔富) Bin 138 巴羅薩西拉歌海娜",
      "penfolds bin 2 shiraz mataro":                  "Penfolds (奔富) Bin 2 西拉慕合懷特",
      "penfolds bin 21 grenache":                      "Penfolds (奔富) Bin 21 歌海娜",
      "penfolds bin 23 pinot noir":                    "Penfolds (奔富) Bin 23 黑皮諾",
      "penfolds bin 28 kalimna shiraz":                "Penfolds (奔富) Bin 28 卡琳娜西拉",
      "penfolds bin 389 cabernet shiraz":              "Penfolds (奔富) Bin 389 赤霞珠西拉",
      "penfolds bin 407 cabernet sauvignon":           "Penfolds (奔富) Bin 407 赤霞珠",
      "penfolds bin 600 cabernet shiraz":              "Penfolds (奔富) Bin 600 赤霞珠西拉",
      "penfolds bin 704 napa cabernet sauvignon":      "Penfolds (奔富) Bin 704 納帕谷赤霞珠",
      "penfolds bin 8 cabernet shiraz":                "Penfolds (奔富) Bin 8 赤霞珠西拉",
      "penfolds cwt 521 cabernet sauvignon marselan":  "Penfolds (奔富) CWT 521 赤霞珠馬瑟蘭",
      "penfolds grange":                               "Penfolds (奔富) Grange",
      "penfolds st henri shiraz":                      "Penfolds (奔富) St Henri 西拉",
      "penfolds koonunga hill cabernet sauvignon":     "Penfolds 寇蘭山赤霞珠",
      "penfolds koonunga hill shiraz":                 "Penfolds 寇蘭山西拉",
      "penfolds koonunga hill shiraz cabernet":        "Penfolds 寇蘭山西拉赤霞珠",
      "penfolds maxs cabernet sauvignon":              "Penfolds Max's 赤霞珠",
      "penfolds maxs shiraz":                          "Penfolds Max's 西拉",
      "penfolds maxs shiraz cabernet":                 "Penfolds Max's 西拉赤霞珠",
      "penfolds reserve bin a chardonnay":             "Penfolds Reserve Bin A 霞多麗",
      
      "petaluma yellow label b v vineyard shiraz":     "Petaluma Yellow Label 西拉",
      "petaluma yellow label coonawarra cabernet merlot": "Petaluma Yellow Label 赤霞珠梅洛",
      "peter max pinot noir":                          "Peter Max 黑皮諾",
      "petit lacoste pauillac":                        "Petit Lacoste 波亞克",
      "petit vallon montagne saint emilion":           "Petit Vallon 聖埃美隆",
      "pio cesare barbera d alba":                     "Pio Cesare Barbera d'Alba",
      "raimat tempranillo":                            "Raimat 丹魄",
      "rambeau lussac saint emilion":                  "Chateau Rambeau Lussac",
      "rauzan gassies haut medoc":                     "Chateau Rauzan-Gassies",
      
      // Rawson's Retreat (洛神山莊)
      "rawsons retreat cabernet sauvignon":            "Rawson's Retreat 赤霞珠",
      "rawson retreat merlot":                         "Rawson's Retreat 梅洛",
      "rawson retreat shiraz cabernet":                "Rawson's Retreat 西拉赤霞珠",
      
      "ricossa barbaresco":                            "Ricossa Barbaresco",
      "ricossa barolo":                                "Ricossa Barolo",
      "riedel o to go pinot noir tumbler":             "Riedel O To Go 黑皮諾酒杯",
      "la roche l range merlot":                       "La Roche L Range 梅洛",
      "la roche l range pinot noir":                   "La Roche L Range 黑皮諾",
      "la rose de vit bordeaux":                       "La Rose de Vit 波爾多",
      "rupert and rothschild classique":               "Rupert & Rothschild Classique",
      
      "saint clair origin sauvignon blanc":            "Saint Clair Origin 長相思",
      "santa helena gran reserva cabernet sauvignon":  "Santa Helena 特級珍藏赤霞珠",
      
      // Santa Rita
      "santa rita 120 reserva merlot":                 "Santa Rita 120 珍藏梅洛",
      "santa rita 120 cabernet sauvignon":             "Santa Rita 120 赤霞珠",
      
      "sarget de gruaud larose saint julien":          "Sarget de Gruaud Larose (金玫瑰副牌)",
      "second camensac haut medoc":                    "Le Second de Camensac (卡門薩克副牌)",
      "sherwood estate stoney range pinot noir":       "Sherwood Estate Stoney Range 黑皮諾",
      
      "the shy pig shiraz cabernet merlot":            "The Shy Pig 西拉赤霞珠梅洛",
      "the shy pig shiraz":                            "The Shy Pig 西拉",
      "the stag shiraz":                               "The Stag 西拉",
      "stanley shiraz cabernet":                       "Stanley 西拉赤霞珠",
      "stanley traditional dry red":                   "Stanley 傳統乾紅",
      "substance cabernet sauvignon":                  "Substance 赤霞珠",
      "suntory antioxidant additive free red":         "三得利無添加抗氧化紅酒",
      "terr baume st paul fitou":                      "Terr Baume St Paul Fitou",
      "terr baume st paul muscat saint jean minervois": "Terr Baume St Paul Muscat",
      
      // Terra Vega
      "terra vega reserva cabernet sauvignon":         "Terra Vega 珍藏赤霞珠",
      "terra vega reserva carmenere":                  "Terra Vega 珍藏佳美娜",
      "terra vega reserva merlot":                     "Terra Vega 珍藏梅洛",
      
      "terrunyo carmenere":                            "Terrunyo 佳美娜",
      "tessellae old vines cotes du roussillon":       "Tessellae 老藤魯西榮",
      "tierra de cubas dux imperial gran reserva":     "Tierra de Cubas 特級珍藏",
      "tierra de cubas manadero":                      "Tierra de Cubas Manadero",
      "tilia malbec":                                  "Tilia 馬爾貝克",
      "tommasi merlot le prunee":                      "Tommasi Merlot Le Prunee",
      "torres sangre de toro":                         "Torres Sangre de Toro (公牛血)",
      "tread softly pinot noir":                       "Tread Softly 黑皮諾",
      "trocard bordeaux superieur":                    "Trocard 優質波爾多",
      "vieux chateau renaissance bordeaux":            "Vieux Chateau Renaissance 波爾多",
      "vina gracia merlot":                            "Vina Gracia 梅洛",
      "vina pomal reserva centenario":                 "Vina Pomal 珍藏紅酒",
      
      // Waitrose
      "waitrose cava brut":                            "Waitrose Cava 氣泡酒",
      "waitrose burgundy chardonnay":                  "Waitrose 勃艮第霞多麗",
      "waitrose chianti tuscany":                      "Waitrose 基安蒂紅酒",
      "waitrose dry riesling":                         "Waitrose 乾雷司令",
      
      "whistler barossa shiraz":                       "Whistler 巴羅薩西拉",
      
      // Wolf Blass (禾富)
      "wolf blass black label cabernet shiraz malbec": "Wolf Blass 黑牌",
      "wolf blass red label cabernet merlot":          "Wolf Blass 紅牌 赤霞珠梅洛",
      "wolf blass eaglehawk shiraz merlot cabernet":   "Wolf Blass Eaglehawk (鷹標) 紅混合酒",
      "wolf blass founders original blend":            "Wolf Blass Founders Original",
      "wolf blass gold label cabernet sauvignon":      "Wolf Blass 金牌 赤霞珠",
      "wolf blass gold label shiraz":                  "Wolf Blass 金牌 西拉",
      "wolf blass grey label cabernet shiraz":         "Wolf Blass 灰牌 赤霞珠西拉",
      "wolf blass grey label shiraz":                  "Wolf Blass 灰牌 西拉",
      "wolf blass presidents selection gold label cabernet sauvignon": "Wolf Blass 總裁精選 赤霞珠",
      "wolf blass presidents selection gold label shiraz": "Wolf Blass 總裁精選 西拉",
      "wolf blass yellow label cabernet sauvignon":    "Wolf Blass 黃牌 赤霞珠",
      "wolf blass yellow label merlot":                "Wolf Blass 黃牌 梅洛",
      "wolf blass yellow label shiraz":                "Wolf Blass 黃牌 西拉",
      
      // Wynns (雲咸)
      "wynns black label cabernet sauvignon":          "Wynns 黑牌 赤霞珠",
      "wynns black label shiraz":                      "Wynns 黑牌 西拉",
      "wynns red stripe cabernet shiraz merlot":       "Wynns 紅帶 赤霞珠西拉梅洛",
      "wynns glengyle single vineyard coonawarra cabernet sauvignon": "Wynns Glengyle 單一葡萄園赤霞珠",
      "wynns shiraz":                                  "Wynns 西拉",
      "wynns the siding cabernet sauvignon":           "Wynns The Siding 赤霞珠",
      "wynns v and a lane coonawarra cabernet shiraz": "Wynns V&A Lane 赤霞珠西拉",
      "wynns v and a lane coonawarra shiraz":          "Wynns V&A Lane 西拉",
      
      // Yalumba
      "yalumba y series cabernet sauvignon":           "Yalumba Y Series 赤霞珠",
      "yalumba ym barossa shiraz":                     "Yalumba YM 巴羅薩西拉",
      
      // Yellow Tail (黃尾袋鼠)
      "yellow tail cabernet sauvignon":                "Yellow Tail 赤霞珠",
      "yellow tail merlot":                            "Yellow Tail 梅洛",
      "yellow tail sangria":                           "Yellow Tail Sangria (桑格利亞)",
      "yellow tail shiraz":                            "Yellow Tail 西拉"
    ]

]
